# coding: utf-8

"""
    Catalog REST API

    REST API for Kubeflow Hub Catalog

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from catalog_openapi.models.asset_source_preview_response import AssetSourcePreviewResponse
from catalog_openapi.models.catalog_source_preview_response import CatalogSourcePreviewResponse
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

PREVIEWCATALOGSOURCERESPONSE_ONE_OF_SCHEMAS = ["AssetSourcePreviewResponse", "CatalogSourcePreviewResponse"]

class PreviewCatalogSourceResponse(BaseModel):
    """
    Polymorphic preview response. The `assetType` discriminator determines whether the payload is a model preview (`CatalogSourcePreviewResponse`) or a generic asset preview (`AssetSourcePreviewResponse`), the latter used for both MCP server and skill sources.
    """
    # data type: CatalogSourcePreviewResponse
    oneof_schema_1_validator: Optional[CatalogSourcePreviewResponse] = None
    # data type: AssetSourcePreviewResponse
    oneof_schema_2_validator: Optional[AssetSourcePreviewResponse] = None
    actual_instance: Optional[Union[AssetSourcePreviewResponse, CatalogSourcePreviewResponse]] = None
    one_of_schemas: Set[str] = { "AssetSourcePreviewResponse", "CatalogSourcePreviewResponse" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = PreviewCatalogSourceResponse.model_construct()
        error_messages = []
        match = 0
        # validate data type: CatalogSourcePreviewResponse
        if not isinstance(v, CatalogSourcePreviewResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CatalogSourcePreviewResponse`")
        else:
            match += 1
        # validate data type: AssetSourcePreviewResponse
        if not isinstance(v, AssetSourcePreviewResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AssetSourcePreviewResponse`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in PreviewCatalogSourceResponse with oneOf schemas: AssetSourcePreviewResponse, CatalogSourcePreviewResponse. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in PreviewCatalogSourceResponse with oneOf schemas: AssetSourcePreviewResponse, CatalogSourcePreviewResponse. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("assetType")
        if not _data_type:
            raise ValueError("Failed to lookup data type from the field `assetType` in the input.")

        # check if data type is `AssetSourcePreviewResponse`
        if _data_type == "mcp_servers":
            instance.actual_instance = AssetSourcePreviewResponse.from_json(json_str)
            return instance

        # check if data type is `CatalogSourcePreviewResponse`
        if _data_type == "models":
            instance.actual_instance = CatalogSourcePreviewResponse.from_json(json_str)
            return instance

        # check if data type is `AssetSourcePreviewResponse`
        if _data_type == "skills":
            instance.actual_instance = AssetSourcePreviewResponse.from_json(json_str)
            return instance

        # deserialize data into CatalogSourcePreviewResponse
        try:
            instance.actual_instance = CatalogSourcePreviewResponse.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AssetSourcePreviewResponse
        try:
            instance.actual_instance = AssetSourcePreviewResponse.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into PreviewCatalogSourceResponse with oneOf schemas: AssetSourcePreviewResponse, CatalogSourcePreviewResponse. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PreviewCatalogSourceResponse with oneOf schemas: AssetSourcePreviewResponse, CatalogSourcePreviewResponse. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AssetSourcePreviewResponse, CatalogSourcePreviewResponse]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
