
"""Catalog REST API

REST API for Kubeflow Hub Catalog

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing_extensions import Self

from catalog_openapi.models.metadata_value import MetadataValue
from catalog_openapi.models.serving_runtime_env_var import ServingRuntimeEnvVar
from catalog_openapi.models.serving_runtime_resource_recommendation import ServingRuntimeResourceRecommendation
from catalog_openapi.models.serving_runtime_support_level import ServingRuntimeSupportLevel
from catalog_openapi.models.supported_model_format import SupportedModelFormat


class ServingRuntimeVersion(BaseModel):
    """A specific, deployable version of a serving runtime. Carries the container image and the metadata needed to generate a ServingRuntime manifest. Discovery metadata only — not a live deployment.
    """ # noqa: E501
    custom_properties: dict[str, MetadataValue] | None = Field(default=None, description="User provided custom properties which are not defined by its type.", alias="customProperties")
    description: StrictStr | None = Field(default=None, description="An optional description about the resource.")
    external_id: StrictStr | None = Field(default=None, description="The external id that come from the clients’ system. This field is optional. If set, it must be unique among all resources within a database instance.", alias="externalId")
    name: Annotated[str, Field(min_length=1, strict=True)] | None = Field(default=None, description="The client provided name of the artifact. This field is optional. If set, it must be unique among all the artifacts of the same artifact type within a database instance and cannot be changed once set.")
    id: StrictStr | None = Field(default=None, description="The unique server generated id of the resource.")
    create_time_since_epoch: StrictStr | None = Field(default=None, description="Output only. Create time of the resource in millisecond since epoch.", alias="createTimeSinceEpoch")
    last_update_time_since_epoch: StrictStr | None = Field(default=None, description="Output only. Last update time of the resource since epoch in millisecond since epoch.", alias="lastUpdateTimeSinceEpoch")
    artifact_type: StrictStr = Field(alias="artifactType")
    version: StrictStr = Field(description="Version string of the runtime (typically the image tag).")
    image: StrictStr = Field(description="Fully-qualified container image reference for this version. The registry host may be rewritten by the dashboard for disconnected environments (registry mirror override).")
    support_level: ServingRuntimeSupportLevel | None = Field(default=None, alias="supportLevel")
    supported_model_formats: list[SupportedModelFormat] | None = Field(default=None, description="Model formats supported by this specific version.", alias="supportedModelFormats")
    protocol_versions: list[StrictStr] | None = Field(default=None, description="Inference protocols supported (maps to ServingRuntime.spec.protocolVersions).", alias="protocolVersions")
    recommended_resources: ServingRuntimeResourceRecommendation | None = Field(default=None, alias="recommendedResources")
    default_args: list[StrictStr] | None = Field(default=None, description="Default container args for the generated ServingRuntime.", alias="defaultArgs")
    env: list[ServingRuntimeEnvVar] | None = Field(default=None, description="Environment variables the runtime accepts (discovery hints; no secret values).")
    template: StrictStr | None = Field(default=None, description="Optional full ServingRuntime (KServe v1alpha1) manifest for this version, as a JSON-encoded string, ready for review/edit before creation. If omitted, the consumer generates the manifest from the fields above.")
    deprecated: StrictBool | None = Field(default=False, description="Whether this version is deprecated and should be de-emphasized in the UI.")
    published_date: datetime | None = Field(default=None, description="Publication timestamp for this version/image.", alias="publishedDate")
    __properties: ClassVar[list[str]] = ["customProperties", "description", "externalId", "name", "id", "createTimeSinceEpoch", "lastUpdateTimeSinceEpoch", "artifactType", "version", "image", "supportLevel", "supportedModelFormats", "protocolVersions", "recommendedResources", "defaultArgs", "env", "template", "deprecated", "publishedDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ServingRuntimeVersion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set([
            "create_time_since_epoch",
            "last_update_time_since_epoch",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in custom_properties (dict)
        _field_dict = {}
        if self.custom_properties:
            for _key_custom_properties in self.custom_properties:
                if self.custom_properties[_key_custom_properties]:
                    _field_dict[_key_custom_properties] = self.custom_properties[_key_custom_properties].to_dict()
            _dict["customProperties"] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in supported_model_formats (list)
        _items = []
        if self.supported_model_formats:
            for _item_supported_model_formats in self.supported_model_formats:
                if _item_supported_model_formats:
                    _items.append(_item_supported_model_formats.to_dict())
            _dict["supportedModelFormats"] = _items
        # override the default output from pydantic by calling `to_dict()` of recommended_resources
        if self.recommended_resources:
            _dict["recommendedResources"] = self.recommended_resources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in env (list)
        _items = []
        if self.env:
            for _item_env in self.env:
                if _item_env:
                    _items.append(_item_env.to_dict())
            _dict["env"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ServingRuntimeVersion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customProperties": dict(
                (_k, MetadataValue.from_dict(_v))
                for _k, _v in obj["customProperties"].items()
            )
            if obj.get("customProperties") is not None
            else None,
            "description": obj.get("description"),
            "externalId": obj.get("externalId"),
            "name": obj.get("name"),
            "id": obj.get("id"),
            "createTimeSinceEpoch": obj.get("createTimeSinceEpoch"),
            "lastUpdateTimeSinceEpoch": obj.get("lastUpdateTimeSinceEpoch"),
            "artifactType": obj.get("artifactType") if obj.get("artifactType") is not None else "serving-runtime-version",
            "version": obj.get("version"),
            "image": obj.get("image"),
            "supportLevel": obj.get("supportLevel"),
            "supportedModelFormats": [SupportedModelFormat.from_dict(_item) for _item in obj["supportedModelFormats"]] if obj.get("supportedModelFormats") is not None else None,
            "protocolVersions": obj.get("protocolVersions"),
            "recommendedResources": ServingRuntimeResourceRecommendation.from_dict(obj["recommendedResources"]) if obj.get("recommendedResources") is not None else None,
            "defaultArgs": obj.get("defaultArgs"),
            "env": [ServingRuntimeEnvVar.from_dict(_item) for _item in obj["env"]] if obj.get("env") is not None else None,
            "template": obj.get("template"),
            "deprecated": obj.get("deprecated") if obj.get("deprecated") is not None else False,
            "publishedDate": obj.get("publishedDate")
        })
        return _obj
