
"""Catalog REST API

REST API for Kubeflow Hub Catalog

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class ServingRuntimeSupportLevel(str, Enum):
    """Support/provenance badge for a runtime version. A display label usable for filtering; carries no ordering semantics.
    """

    """
    allowed enum values
    """
    SUPPORTED = "supported"
    TECHPREVIEW = "techPreview"
    DEVELOPERPREVIEW = "developerPreview"
    COMMUNITY = "community"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ServingRuntimeSupportLevel from a JSON string"""
        return cls(json.loads(json_str))
