
"""Catalog REST API

REST API for Kubeflow Hub Catalog

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self

from catalog_openapi.models.metadata_value import MetadataValue
from catalog_openapi.models.serving_runtime_capabilities import ServingRuntimeCapabilities
from catalog_openapi.models.supported_model_format import SupportedModelFormat


class ServingRuntime(BaseModel):
    """A serving runtime family in the serving runtime catalog.
    """ # noqa: E501
    custom_properties: dict[str, MetadataValue] | None = Field(default=None, description="User provided custom properties which are not defined by its type.", alias="customProperties")
    description: StrictStr | None = Field(default=None, description="An optional description about the resource.")
    external_id: StrictStr | None = Field(default=None, description="The external id that come from the clients’ system. This field is optional. If set, it must be unique among all resources within a database instance.", alias="externalId")
    name: Annotated[str, Field(min_length=1, strict=True)] | None = Field(default=None, description="The client provided name of the artifact. This field is optional. If set, it must be unique among all the artifacts of the same artifact type within a database instance and cannot be changed once set.")
    id: StrictStr | None = Field(default=None, description="The unique server generated id of the resource.")
    create_time_since_epoch: StrictStr | None = Field(default=None, description="Output only. Create time of the resource in millisecond since epoch.", alias="createTimeSinceEpoch")
    last_update_time_since_epoch: StrictStr | None = Field(default=None, description="Output only. Last update time of the resource since epoch in millisecond since epoch.", alias="lastUpdateTimeSinceEpoch")
    display_name: Annotated[str, Field(strict=True, max_length=255)] | None = Field(default=None, description="Human-friendly display label.", alias="displayName")
    source_id: StrictStr | None = Field(default=None, description="Catalog source that provides this runtime.", alias="sourceId")
    provider: StrictStr | None = Field(default=None, description="Organization providing the runtime.")
    readme: StrictStr | None = Field(default=None, description="Full Markdown documentation for this runtime.")
    logo: StrictStr | None = Field(default=None, description="Runtime logo. A data URL is recommended; a plain http(s) URL is also accepted (served via the /logo endpoint).")
    tags: list[StrictStr] | None = Field(default=None, description="Categorization tags.")
    license: StrictStr | None = Field(default=None, description="SPDX identifier for the runtime license.")
    license_link: StrictStr | None = Field(default=None, description="URL to the full license text.", alias="licenseLink")
    documentation_url: StrictStr | None = Field(default=None, description="URL to external documentation.", alias="documentationUrl")
    repository_url: StrictStr | None = Field(default=None, description="URL to the source repository.", alias="repositoryUrl")
    supported_model_formats: list[SupportedModelFormat] | None = Field(default=None, description="Model formats this runtime can serve, aggregated across its versions. Maps to ServingRuntime.spec.supportedModelFormats.", alias="supportedModelFormats")
    capabilities: ServingRuntimeCapabilities | None = None
    version_count: StrictInt | None = Field(default=None, description="Number of catalog versions available for this runtime.", alias="versionCount")
    published_date: datetime | None = Field(default=None, description="Initial publication timestamp.", alias="publishedDate")
    last_updated: datetime | None = Field(default=None, description="Last metadata update timestamp.", alias="lastUpdated")
    __properties: ClassVar[list[str]] = ["customProperties", "description", "externalId", "name", "id", "createTimeSinceEpoch", "lastUpdateTimeSinceEpoch", "displayName", "sourceId", "provider", "readme", "logo", "tags", "license", "licenseLink", "documentationUrl", "repositoryUrl", "supportedModelFormats", "capabilities", "versionCount", "publishedDate", "lastUpdated"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ServingRuntime from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set([
            "create_time_since_epoch",
            "last_update_time_since_epoch",
            "version_count",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in custom_properties (dict)
        _field_dict = {}
        if self.custom_properties:
            for _key_custom_properties in self.custom_properties:
                if self.custom_properties[_key_custom_properties]:
                    _field_dict[_key_custom_properties] = self.custom_properties[_key_custom_properties].to_dict()
            _dict["customProperties"] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in supported_model_formats (list)
        _items = []
        if self.supported_model_formats:
            for _item_supported_model_formats in self.supported_model_formats:
                if _item_supported_model_formats:
                    _items.append(_item_supported_model_formats.to_dict())
            _dict["supportedModelFormats"] = _items
        # override the default output from pydantic by calling `to_dict()` of capabilities
        if self.capabilities:
            _dict["capabilities"] = self.capabilities.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ServingRuntime from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customProperties": dict(
                (_k, MetadataValue.from_dict(_v))
                for _k, _v in obj["customProperties"].items()
            )
            if obj.get("customProperties") is not None
            else None,
            "description": obj.get("description"),
            "externalId": obj.get("externalId"),
            "name": obj.get("name"),
            "id": obj.get("id"),
            "createTimeSinceEpoch": obj.get("createTimeSinceEpoch"),
            "lastUpdateTimeSinceEpoch": obj.get("lastUpdateTimeSinceEpoch"),
            "displayName": obj.get("displayName"),
            "sourceId": obj.get("sourceId"),
            "provider": obj.get("provider"),
            "readme": obj.get("readme"),
            "logo": obj.get("logo"),
            "tags": obj.get("tags"),
            "license": obj.get("license"),
            "licenseLink": obj.get("licenseLink"),
            "documentationUrl": obj.get("documentationUrl"),
            "repositoryUrl": obj.get("repositoryUrl"),
            "supportedModelFormats": [SupportedModelFormat.from_dict(_item) for _item in obj["supportedModelFormats"]] if obj.get("supportedModelFormats") is not None else None,
            "capabilities": ServingRuntimeCapabilities.from_dict(obj["capabilities"]) if obj.get("capabilities") is not None else None,
            "versionCount": obj.get("versionCount"),
            "publishedDate": obj.get("publishedDate"),
            "lastUpdated": obj.get("lastUpdated")
        })
        return _obj
