
"""Catalog REST API

REST API for Kubeflow Hub Catalog

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self


class SupportedModelFormat(BaseModel):
    """A model format a runtime can serve. Maps to ServingRuntime.spec.supportedModelFormats[].
    """ # noqa: E501
    name: StrictStr = Field(description="Format name.")
    version: StrictStr | None = Field(default=None, description="Optional format version.")
    auto_select: StrictBool | None = Field(default=False, description="Whether this runtime may be auto-selected for the format.", alias="autoSelect")
    priority: StrictInt | None = Field(default=None, description="Selection priority when multiple runtimes support the format.")
    __properties: ClassVar[list[str]] = ["name", "version", "autoSelect", "priority"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SupportedModelFormat from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SupportedModelFormat from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "version": obj.get("version"),
            "autoSelect": obj.get("autoSelect") if obj.get("autoSelect") is not None else False,
            "priority": obj.get("priority")
        })
        return _obj
