/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServingRuntimeCapabilities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServingRuntimeCapabilities{}

// ServingRuntimeCapabilities High-level capability flags to aid discovery and filtering.
type ServingRuntimeCapabilities struct {
	// Whether the runtime requires a GPU/accelerator.
	RequiresGPU *bool `json:"requiresGPU,omitempty"`
	// Accelerator types this runtime supports.
	SupportedAccelerators []string `json:"supportedAccelerators,omitempty"`
	// Whether the runtime can serve multiple models (ModelMesh-style). Maps to ServingRuntime.spec.multiModel.
	MultiModel *bool `json:"multiModel,omitempty"`
}

// NewServingRuntimeCapabilities instantiates a new ServingRuntimeCapabilities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServingRuntimeCapabilities() *ServingRuntimeCapabilities {
	this := ServingRuntimeCapabilities{}
	var requiresGPU bool = false
	this.RequiresGPU = &requiresGPU
	var multiModel bool = false
	this.MultiModel = &multiModel
	return &this
}

// NewServingRuntimeCapabilitiesWithDefaults instantiates a new ServingRuntimeCapabilities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServingRuntimeCapabilitiesWithDefaults() *ServingRuntimeCapabilities {
	this := ServingRuntimeCapabilities{}
	var requiresGPU bool = false
	this.RequiresGPU = &requiresGPU
	var multiModel bool = false
	this.MultiModel = &multiModel
	return &this
}

// GetRequiresGPU returns the RequiresGPU field value if set, zero value otherwise.
func (o *ServingRuntimeCapabilities) GetRequiresGPU() bool {
	if o == nil || IsNil(o.RequiresGPU) {
		var ret bool
		return ret
	}
	return *o.RequiresGPU
}

// GetRequiresGPUOk returns a tuple with the RequiresGPU field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeCapabilities) GetRequiresGPUOk() (*bool, bool) {
	if o == nil || IsNil(o.RequiresGPU) {
		return nil, false
	}
	return o.RequiresGPU, true
}

// HasRequiresGPU returns a boolean if a field has been set.
func (o *ServingRuntimeCapabilities) HasRequiresGPU() bool {
	if o != nil && !IsNil(o.RequiresGPU) {
		return true
	}

	return false
}

// SetRequiresGPU gets a reference to the given bool and assigns it to the RequiresGPU field.
func (o *ServingRuntimeCapabilities) SetRequiresGPU(v bool) {
	o.RequiresGPU = &v
}

// GetSupportedAccelerators returns the SupportedAccelerators field value if set, zero value otherwise.
func (o *ServingRuntimeCapabilities) GetSupportedAccelerators() []string {
	if o == nil || IsNil(o.SupportedAccelerators) {
		var ret []string
		return ret
	}
	return o.SupportedAccelerators
}

// GetSupportedAcceleratorsOk returns a tuple with the SupportedAccelerators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeCapabilities) GetSupportedAcceleratorsOk() ([]string, bool) {
	if o == nil || IsNil(o.SupportedAccelerators) {
		return nil, false
	}
	return o.SupportedAccelerators, true
}

// HasSupportedAccelerators returns a boolean if a field has been set.
func (o *ServingRuntimeCapabilities) HasSupportedAccelerators() bool {
	if o != nil && !IsNil(o.SupportedAccelerators) {
		return true
	}

	return false
}

// SetSupportedAccelerators gets a reference to the given []string and assigns it to the SupportedAccelerators field.
func (o *ServingRuntimeCapabilities) SetSupportedAccelerators(v []string) {
	o.SupportedAccelerators = v
}

// GetMultiModel returns the MultiModel field value if set, zero value otherwise.
func (o *ServingRuntimeCapabilities) GetMultiModel() bool {
	if o == nil || IsNil(o.MultiModel) {
		var ret bool
		return ret
	}
	return *o.MultiModel
}

// GetMultiModelOk returns a tuple with the MultiModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeCapabilities) GetMultiModelOk() (*bool, bool) {
	if o == nil || IsNil(o.MultiModel) {
		return nil, false
	}
	return o.MultiModel, true
}

// HasMultiModel returns a boolean if a field has been set.
func (o *ServingRuntimeCapabilities) HasMultiModel() bool {
	if o != nil && !IsNil(o.MultiModel) {
		return true
	}

	return false
}

// SetMultiModel gets a reference to the given bool and assigns it to the MultiModel field.
func (o *ServingRuntimeCapabilities) SetMultiModel(v bool) {
	o.MultiModel = &v
}

func (o ServingRuntimeCapabilities) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServingRuntimeCapabilities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequiresGPU) {
		toSerialize["requiresGPU"] = o.RequiresGPU
	}
	if !IsNil(o.SupportedAccelerators) {
		toSerialize["supportedAccelerators"] = o.SupportedAccelerators
	}
	if !IsNil(o.MultiModel) {
		toSerialize["multiModel"] = o.MultiModel
	}
	return toSerialize, nil
}

type NullableServingRuntimeCapabilities struct {
	value *ServingRuntimeCapabilities
	isSet bool
}

func (v NullableServingRuntimeCapabilities) Get() *ServingRuntimeCapabilities {
	return v.value
}

func (v *NullableServingRuntimeCapabilities) Set(val *ServingRuntimeCapabilities) {
	v.value = val
	v.isSet = true
}

func (v NullableServingRuntimeCapabilities) IsSet() bool {
	return v.isSet
}

func (v *NullableServingRuntimeCapabilities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServingRuntimeCapabilities(val *ServingRuntimeCapabilities) *NullableServingRuntimeCapabilities {
	return &NullableServingRuntimeCapabilities{value: val, isSet: true}
}

func (v NullableServingRuntimeCapabilities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServingRuntimeCapabilities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
