/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ServingRuntimeSupportLevel Support/provenance badge for a runtime version. A display label usable for filtering; carries no ordering semantics.
type ServingRuntimeSupportLevel string

// List of ServingRuntimeSupportLevel
const (
	SERVINGRUNTIMESUPPORTLEVEL_SUPPORTED         ServingRuntimeSupportLevel = "supported"
	SERVINGRUNTIMESUPPORTLEVEL_TECH_PREVIEW      ServingRuntimeSupportLevel = "techPreview"
	SERVINGRUNTIMESUPPORTLEVEL_DEVELOPER_PREVIEW ServingRuntimeSupportLevel = "developerPreview"
	SERVINGRUNTIMESUPPORTLEVEL_COMMUNITY         ServingRuntimeSupportLevel = "community"
)

// All allowed values of ServingRuntimeSupportLevel enum
var AllowedServingRuntimeSupportLevelEnumValues = []ServingRuntimeSupportLevel{
	"supported",
	"techPreview",
	"developerPreview",
	"community",
}

func (v *ServingRuntimeSupportLevel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ServingRuntimeSupportLevel(value)
	for _, existing := range AllowedServingRuntimeSupportLevelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ServingRuntimeSupportLevel", value)
}

// NewServingRuntimeSupportLevelFromValue returns a pointer to a valid ServingRuntimeSupportLevel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewServingRuntimeSupportLevelFromValue(v string) (*ServingRuntimeSupportLevel, error) {
	ev := ServingRuntimeSupportLevel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ServingRuntimeSupportLevel: valid values are %v", v, AllowedServingRuntimeSupportLevelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ServingRuntimeSupportLevel) IsValid() bool {
	for _, existing := range AllowedServingRuntimeSupportLevelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ServingRuntimeSupportLevel value
func (v ServingRuntimeSupportLevel) Ptr() *ServingRuntimeSupportLevel {
	return &v
}

type NullableServingRuntimeSupportLevel struct {
	value *ServingRuntimeSupportLevel
	isSet bool
}

func (v NullableServingRuntimeSupportLevel) Get() *ServingRuntimeSupportLevel {
	return v.value
}

func (v *NullableServingRuntimeSupportLevel) Set(val *ServingRuntimeSupportLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableServingRuntimeSupportLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableServingRuntimeSupportLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServingRuntimeSupportLevel(val *ServingRuntimeSupportLevel) *NullableServingRuntimeSupportLevel {
	return &NullableServingRuntimeSupportLevel{value: val, isSet: true}
}

func (v NullableServingRuntimeSupportLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServingRuntimeSupportLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
