/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServingRuntimeList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServingRuntimeList{}

// ServingRuntimeList A list of serving_runtime entities.
type ServingRuntimeList struct {
	// Token to use to retrieve next page of results.
	NextPageToken string `json:"nextPageToken"`
	// Maximum number of resources to return in the result.
	PageSize int32 `json:"pageSize"`
	// Number of items in result list.
	Size int32 `json:"size"`
	// Array of `ServingRuntime` entities.
	Items []ServingRuntime `json:"items"`
}

type _ServingRuntimeList ServingRuntimeList

// NewServingRuntimeList instantiates a new ServingRuntimeList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServingRuntimeList(nextPageToken string, pageSize int32, size int32, items []ServingRuntime) *ServingRuntimeList {
	this := ServingRuntimeList{}
	this.NextPageToken = nextPageToken
	this.PageSize = pageSize
	this.Size = size
	this.Items = items
	return &this
}

// NewServingRuntimeListWithDefaults instantiates a new ServingRuntimeList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServingRuntimeListWithDefaults() *ServingRuntimeList {
	this := ServingRuntimeList{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value
func (o *ServingRuntimeList) GetNextPageToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeList) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPageToken, true
}

// SetNextPageToken sets field value
func (o *ServingRuntimeList) SetNextPageToken(v string) {
	o.NextPageToken = v
}

// GetPageSize returns the PageSize field value
func (o *ServingRuntimeList) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeList) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *ServingRuntimeList) SetPageSize(v int32) {
	o.PageSize = v
}

// GetSize returns the Size field value
func (o *ServingRuntimeList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ServingRuntimeList) SetSize(v int32) {
	o.Size = v
}

// GetItems returns the Items field value
func (o *ServingRuntimeList) GetItems() []ServingRuntime {
	if o == nil {
		var ret []ServingRuntime
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeList) GetItemsOk() ([]ServingRuntime, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ServingRuntimeList) SetItems(v []ServingRuntime) {
	o.Items = v
}

func (o ServingRuntimeList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServingRuntimeList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nextPageToken"] = o.NextPageToken
	toSerialize["pageSize"] = o.PageSize
	toSerialize["size"] = o.Size
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableServingRuntimeList struct {
	value *ServingRuntimeList
	isSet bool
}

func (v NullableServingRuntimeList) Get() *ServingRuntimeList {
	return v.value
}

func (v *NullableServingRuntimeList) Set(val *ServingRuntimeList) {
	v.value = val
	v.isSet = true
}

func (v NullableServingRuntimeList) IsSet() bool {
	return v.isSet
}

func (v *NullableServingRuntimeList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServingRuntimeList(val *ServingRuntimeList) *NullableServingRuntimeList {
	return &NullableServingRuntimeList{value: val, isSet: true}
}

func (v NullableServingRuntimeList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServingRuntimeList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
