/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResourceTier type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceTier{}

// ResourceTier struct for ResourceTier
type ResourceTier struct {
	Cpu    *string `json:"cpu,omitempty"`
	Memory *string `json:"memory,omitempty"`
	// Accelerator request, e.g. {\"nvidia.com/gpu\": \"1\"}.
	Accelerator *map[string]string `json:"accelerator,omitempty"`
}

// NewResourceTier instantiates a new ResourceTier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceTier() *ResourceTier {
	this := ResourceTier{}
	return &this
}

// NewResourceTierWithDefaults instantiates a new ResourceTier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceTierWithDefaults() *ResourceTier {
	this := ResourceTier{}
	return &this
}

// GetCpu returns the Cpu field value if set, zero value otherwise.
func (o *ResourceTier) GetCpu() string {
	if o == nil || IsNil(o.Cpu) {
		var ret string
		return ret
	}
	return *o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTier) GetCpuOk() (*string, bool) {
	if o == nil || IsNil(o.Cpu) {
		return nil, false
	}
	return o.Cpu, true
}

// HasCpu returns a boolean if a field has been set.
func (o *ResourceTier) HasCpu() bool {
	if o != nil && !IsNil(o.Cpu) {
		return true
	}

	return false
}

// SetCpu gets a reference to the given string and assigns it to the Cpu field.
func (o *ResourceTier) SetCpu(v string) {
	o.Cpu = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *ResourceTier) GetMemory() string {
	if o == nil || IsNil(o.Memory) {
		var ret string
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTier) GetMemoryOk() (*string, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *ResourceTier) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given string and assigns it to the Memory field.
func (o *ResourceTier) SetMemory(v string) {
	o.Memory = &v
}

// GetAccelerator returns the Accelerator field value if set, zero value otherwise.
func (o *ResourceTier) GetAccelerator() map[string]string {
	if o == nil || IsNil(o.Accelerator) {
		var ret map[string]string
		return ret
	}
	return *o.Accelerator
}

// GetAcceleratorOk returns a tuple with the Accelerator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTier) GetAcceleratorOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Accelerator) {
		return nil, false
	}
	return o.Accelerator, true
}

// HasAccelerator returns a boolean if a field has been set.
func (o *ResourceTier) HasAccelerator() bool {
	if o != nil && !IsNil(o.Accelerator) {
		return true
	}

	return false
}

// SetAccelerator gets a reference to the given map[string]string and assigns it to the Accelerator field.
func (o *ResourceTier) SetAccelerator(v map[string]string) {
	o.Accelerator = &v
}

func (o ResourceTier) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceTier) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cpu) {
		toSerialize["cpu"] = o.Cpu
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.Accelerator) {
		toSerialize["accelerator"] = o.Accelerator
	}
	return toSerialize, nil
}

type NullableResourceTier struct {
	value *ResourceTier
	isSet bool
}

func (v NullableResourceTier) Get() *ResourceTier {
	return v.value
}

func (v *NullableResourceTier) Set(val *ResourceTier) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceTier) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceTier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceTier(val *ResourceTier) *NullableResourceTier {
	return &NullableResourceTier{value: val, isSet: true}
}

func (v NullableResourceTier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceTier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
