/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AgentList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentList{}

// AgentList A list of agent entities.
type AgentList struct {
	// Token to use to retrieve next page of results.
	NextPageToken string `json:"nextPageToken"`
	// Maximum number of resources to return in the result.
	PageSize int32 `json:"pageSize"`
	// Number of items in result list.
	Size int32 `json:"size"`
	// Array of `Agent` entities.
	Items []Agent `json:"items"`
}

type _AgentList AgentList

// NewAgentList instantiates a new AgentList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentList(nextPageToken string, pageSize int32, size int32, items []Agent) *AgentList {
	this := AgentList{}
	this.NextPageToken = nextPageToken
	this.PageSize = pageSize
	this.Size = size
	this.Items = items
	return &this
}

// NewAgentListWithDefaults instantiates a new AgentList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentListWithDefaults() *AgentList {
	this := AgentList{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value
func (o *AgentList) GetNextPageToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
func (o *AgentList) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPageToken, true
}

// SetNextPageToken sets field value
func (o *AgentList) SetNextPageToken(v string) {
	o.NextPageToken = v
}

// GetPageSize returns the PageSize field value
func (o *AgentList) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *AgentList) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *AgentList) SetPageSize(v int32) {
	o.PageSize = v
}

// GetSize returns the Size field value
func (o *AgentList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *AgentList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *AgentList) SetSize(v int32) {
	o.Size = v
}

// GetItems returns the Items field value
func (o *AgentList) GetItems() []Agent {
	if o == nil {
		var ret []Agent
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AgentList) GetItemsOk() ([]Agent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *AgentList) SetItems(v []Agent) {
	o.Items = v
}

func (o AgentList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nextPageToken"] = o.NextPageToken
	toSerialize["pageSize"] = o.PageSize
	toSerialize["size"] = o.Size
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableAgentList struct {
	value *AgentList
	isSet bool
}

func (v NullableAgentList) Get() *AgentList {
	return v.value
}

func (v *NullableAgentList) Set(val *AgentList) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentList) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentList(val *AgentList) *NullableAgentList {
	return &NullableAgentList{value: val, isSet: true}
}

func (v NullableAgentList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
