/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CatalogSourcePreviewResponseAllOfSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogSourcePreviewResponseAllOfSummary{}

// CatalogSourcePreviewResponseAllOfSummary Summary of the preview results
type CatalogSourcePreviewResponseAllOfSummary struct {
	// Total number of models evaluated
	TotalModels int32 `json:"totalModels"`
	// Number of models that would be included
	IncludedModels int32 `json:"includedModels"`
	// Number of models that would be excluded
	ExcludedModels int32 `json:"excludedModels"`
	// Whether any evaluated model is a gated Hugging Face model without access (`hfAccessType` gated_auto/gated_manual and `hfGatedAccessGranted` is false or unset), including models outside the current page.
	HasGatedAccessDeniedModels bool `json:"hasGatedAccessDeniedModels"`
}

type _CatalogSourcePreviewResponseAllOfSummary CatalogSourcePreviewResponseAllOfSummary

// NewCatalogSourcePreviewResponseAllOfSummary instantiates a new CatalogSourcePreviewResponseAllOfSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogSourcePreviewResponseAllOfSummary(totalModels int32, includedModels int32, excludedModels int32, hasGatedAccessDeniedModels bool) *CatalogSourcePreviewResponseAllOfSummary {
	this := CatalogSourcePreviewResponseAllOfSummary{}
	this.TotalModels = totalModels
	this.IncludedModels = includedModels
	this.ExcludedModels = excludedModels
	this.HasGatedAccessDeniedModels = hasGatedAccessDeniedModels
	return &this
}

// NewCatalogSourcePreviewResponseAllOfSummaryWithDefaults instantiates a new CatalogSourcePreviewResponseAllOfSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogSourcePreviewResponseAllOfSummaryWithDefaults() *CatalogSourcePreviewResponseAllOfSummary {
	this := CatalogSourcePreviewResponseAllOfSummary{}
	return &this
}

// GetTotalModels returns the TotalModels field value
func (o *CatalogSourcePreviewResponseAllOfSummary) GetTotalModels() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalModels
}

// GetTotalModelsOk returns a tuple with the TotalModels field value
// and a boolean to check if the value has been set.
func (o *CatalogSourcePreviewResponseAllOfSummary) GetTotalModelsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalModels, true
}

// SetTotalModels sets field value
func (o *CatalogSourcePreviewResponseAllOfSummary) SetTotalModels(v int32) {
	o.TotalModels = v
}

// GetIncludedModels returns the IncludedModels field value
func (o *CatalogSourcePreviewResponseAllOfSummary) GetIncludedModels() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IncludedModels
}

// GetIncludedModelsOk returns a tuple with the IncludedModels field value
// and a boolean to check if the value has been set.
func (o *CatalogSourcePreviewResponseAllOfSummary) GetIncludedModelsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludedModels, true
}

// SetIncludedModels sets field value
func (o *CatalogSourcePreviewResponseAllOfSummary) SetIncludedModels(v int32) {
	o.IncludedModels = v
}

// GetExcludedModels returns the ExcludedModels field value
func (o *CatalogSourcePreviewResponseAllOfSummary) GetExcludedModels() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExcludedModels
}

// GetExcludedModelsOk returns a tuple with the ExcludedModels field value
// and a boolean to check if the value has been set.
func (o *CatalogSourcePreviewResponseAllOfSummary) GetExcludedModelsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExcludedModels, true
}

// SetExcludedModels sets field value
func (o *CatalogSourcePreviewResponseAllOfSummary) SetExcludedModels(v int32) {
	o.ExcludedModels = v
}

// GetHasGatedAccessDeniedModels returns the HasGatedAccessDeniedModels field value
func (o *CatalogSourcePreviewResponseAllOfSummary) GetHasGatedAccessDeniedModels() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasGatedAccessDeniedModels
}

// GetHasGatedAccessDeniedModelsOk returns a tuple with the HasGatedAccessDeniedModels field value
// and a boolean to check if the value has been set.
func (o *CatalogSourcePreviewResponseAllOfSummary) GetHasGatedAccessDeniedModelsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasGatedAccessDeniedModels, true
}

// SetHasGatedAccessDeniedModels sets field value
func (o *CatalogSourcePreviewResponseAllOfSummary) SetHasGatedAccessDeniedModels(v bool) {
	o.HasGatedAccessDeniedModels = v
}

func (o CatalogSourcePreviewResponseAllOfSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogSourcePreviewResponseAllOfSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["totalModels"] = o.TotalModels
	toSerialize["includedModels"] = o.IncludedModels
	toSerialize["excludedModels"] = o.ExcludedModels
	toSerialize["hasGatedAccessDeniedModels"] = o.HasGatedAccessDeniedModels
	return toSerialize, nil
}

type NullableCatalogSourcePreviewResponseAllOfSummary struct {
	value *CatalogSourcePreviewResponseAllOfSummary
	isSet bool
}

func (v NullableCatalogSourcePreviewResponseAllOfSummary) Get() *CatalogSourcePreviewResponseAllOfSummary {
	return v.value
}

func (v *NullableCatalogSourcePreviewResponseAllOfSummary) Set(val *CatalogSourcePreviewResponseAllOfSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogSourcePreviewResponseAllOfSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogSourcePreviewResponseAllOfSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogSourcePreviewResponseAllOfSummary(val *CatalogSourcePreviewResponseAllOfSummary) *NullableCatalogSourcePreviewResponseAllOfSummary {
	return &NullableCatalogSourcePreviewResponseAllOfSummary{value: val, isSet: true}
}

func (v NullableCatalogSourcePreviewResponseAllOfSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogSourcePreviewResponseAllOfSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
