/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MCPStorageSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPStorageSource{}

// MCPStorageSource struct for MCPStorageSource
type MCPStorageSource struct {
	// Volume source type for the mount.
	Type string `json:"type"`
	// EmptyDir volume source; use {} for defaults.
	EmptyDir map[string]interface{} `json:"emptyDir,omitempty"`
	// ConfigMap volume source.
	ConfigMap map[string]interface{} `json:"configMap,omitempty"`
	// Secret volume source.
	Secret map[string]interface{} `json:"secret,omitempty"`
}

type _MCPStorageSource MCPStorageSource

// NewMCPStorageSource instantiates a new MCPStorageSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPStorageSource(type_ string) *MCPStorageSource {
	this := MCPStorageSource{}
	this.Type = type_
	return &this
}

// NewMCPStorageSourceWithDefaults instantiates a new MCPStorageSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPStorageSourceWithDefaults() *MCPStorageSource {
	this := MCPStorageSource{}
	return &this
}

// GetType returns the Type field value
func (o *MCPStorageSource) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MCPStorageSource) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MCPStorageSource) SetType(v string) {
	o.Type = v
}

// GetEmptyDir returns the EmptyDir field value if set, zero value otherwise.
func (o *MCPStorageSource) GetEmptyDir() map[string]interface{} {
	if o == nil || IsNil(o.EmptyDir) {
		var ret map[string]interface{}
		return ret
	}
	return o.EmptyDir
}

// GetEmptyDirOk returns a tuple with the EmptyDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPStorageSource) GetEmptyDirOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.EmptyDir) {
		return map[string]interface{}{}, false
	}
	return o.EmptyDir, true
}

// HasEmptyDir returns a boolean if a field has been set.
func (o *MCPStorageSource) HasEmptyDir() bool {
	if o != nil && !IsNil(o.EmptyDir) {
		return true
	}

	return false
}

// SetEmptyDir gets a reference to the given map[string]interface{} and assigns it to the EmptyDir field.
func (o *MCPStorageSource) SetEmptyDir(v map[string]interface{}) {
	o.EmptyDir = v
}

// GetConfigMap returns the ConfigMap field value if set, zero value otherwise.
func (o *MCPStorageSource) GetConfigMap() map[string]interface{} {
	if o == nil || IsNil(o.ConfigMap) {
		var ret map[string]interface{}
		return ret
	}
	return o.ConfigMap
}

// GetConfigMapOk returns a tuple with the ConfigMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPStorageSource) GetConfigMapOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ConfigMap) {
		return map[string]interface{}{}, false
	}
	return o.ConfigMap, true
}

// HasConfigMap returns a boolean if a field has been set.
func (o *MCPStorageSource) HasConfigMap() bool {
	if o != nil && !IsNil(o.ConfigMap) {
		return true
	}

	return false
}

// SetConfigMap gets a reference to the given map[string]interface{} and assigns it to the ConfigMap field.
func (o *MCPStorageSource) SetConfigMap(v map[string]interface{}) {
	o.ConfigMap = v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *MCPStorageSource) GetSecret() map[string]interface{} {
	if o == nil || IsNil(o.Secret) {
		var ret map[string]interface{}
		return ret
	}
	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPStorageSource) GetSecretOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Secret) {
		return map[string]interface{}{}, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *MCPStorageSource) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given map[string]interface{} and assigns it to the Secret field.
func (o *MCPStorageSource) SetSecret(v map[string]interface{}) {
	o.Secret = v
}

func (o MCPStorageSource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPStorageSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.EmptyDir) {
		toSerialize["emptyDir"] = o.EmptyDir
	}
	if !IsNil(o.ConfigMap) {
		toSerialize["configMap"] = o.ConfigMap
	}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	return toSerialize, nil
}

type NullableMCPStorageSource struct {
	value *MCPStorageSource
	isSet bool
}

func (v NullableMCPStorageSource) Get() *MCPStorageSource {
	return v.value
}

func (v *NullableMCPStorageSource) Set(val *MCPStorageSource) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPStorageSource) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPStorageSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPStorageSource(val *MCPStorageSource) *NullableMCPStorageSource {
	return &NullableMCPStorageSource{value: val, isSet: true}
}

func (v NullableMCPStorageSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPStorageSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
