/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// AgentArtifact - A single artifact in the agent catalog API.
type AgentArtifact struct {
	AgentImageArtifact    *AgentImageArtifact
	AgentTemplateArtifact *AgentTemplateArtifact
}

// AgentImageArtifactAsAgentArtifact is a convenience function that returns AgentImageArtifact wrapped in AgentArtifact
func AgentImageArtifactAsAgentArtifact(v *AgentImageArtifact) AgentArtifact {
	return AgentArtifact{
		AgentImageArtifact: v,
	}
}

// AgentTemplateArtifactAsAgentArtifact is a convenience function that returns AgentTemplateArtifact wrapped in AgentArtifact
func AgentTemplateArtifactAsAgentArtifact(v *AgentTemplateArtifact) AgentArtifact {
	return AgentArtifact{
		AgentTemplateArtifact: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *AgentArtifact) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'image-artifact'
	if jsonDict["artifactType"] == "image-artifact" {
		// try to unmarshal JSON data into AgentImageArtifact
		err = json.Unmarshal(data, &dst.AgentImageArtifact)
		if err == nil {
			return nil // data stored in dst.AgentImageArtifact, return on the first match
		} else {
			dst.AgentImageArtifact = nil
			return fmt.Errorf("failed to unmarshal AgentArtifact as AgentImageArtifact: %s", err.Error())
		}
	}

	// check if the discriminator value is 'template-artifact'
	if jsonDict["artifactType"] == "template-artifact" {
		// try to unmarshal JSON data into AgentTemplateArtifact
		err = json.Unmarshal(data, &dst.AgentTemplateArtifact)
		if err == nil {
			return nil // data stored in dst.AgentTemplateArtifact, return on the first match
		} else {
			dst.AgentTemplateArtifact = nil
			return fmt.Errorf("failed to unmarshal AgentArtifact as AgentTemplateArtifact: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AgentArtifact) MarshalJSON() ([]byte, error) {
	if src.AgentImageArtifact != nil {
		return json.Marshal(&src.AgentImageArtifact)
	}

	if src.AgentTemplateArtifact != nil {
		return json.Marshal(&src.AgentTemplateArtifact)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AgentArtifact) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.AgentImageArtifact != nil {
		return obj.AgentImageArtifact
	}

	if obj.AgentTemplateArtifact != nil {
		return obj.AgentTemplateArtifact
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AgentArtifact) GetActualInstanceValue() interface{} {
	if obj.AgentImageArtifact != nil {
		return *obj.AgentImageArtifact
	}

	if obj.AgentTemplateArtifact != nil {
		return *obj.AgentTemplateArtifact
	}

	// all schemas are nil
	return nil
}

type NullableAgentArtifact struct {
	value *AgentArtifact
	isSet bool
}

func (v NullableAgentArtifact) Get() *AgentArtifact {
	return v.value
}

func (v *NullableAgentArtifact) Set(val *AgentArtifact) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentArtifact) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentArtifact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentArtifact(val *AgentArtifact) *NullableAgentArtifact {
	return &NullableAgentArtifact{value: val, isSet: true}
}

func (v NullableAgentArtifact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentArtifact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
