/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AssetSourcePreviewResponseAllOfSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetSourcePreviewResponseAllOfSummary{}

// AssetSourcePreviewResponseAllOfSummary Summary of the preview results
type AssetSourcePreviewResponseAllOfSummary struct {
	// Total number of assets evaluated
	TotalAssets int32 `json:"totalAssets"`
	// Number of assets that would be included
	IncludedAssets int32 `json:"includedAssets"`
	// Number of assets that would be excluded
	ExcludedAssets int32 `json:"excludedAssets"`
}

type _AssetSourcePreviewResponseAllOfSummary AssetSourcePreviewResponseAllOfSummary

// NewAssetSourcePreviewResponseAllOfSummary instantiates a new AssetSourcePreviewResponseAllOfSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetSourcePreviewResponseAllOfSummary(totalAssets int32, includedAssets int32, excludedAssets int32) *AssetSourcePreviewResponseAllOfSummary {
	this := AssetSourcePreviewResponseAllOfSummary{}
	this.TotalAssets = totalAssets
	this.IncludedAssets = includedAssets
	this.ExcludedAssets = excludedAssets
	return &this
}

// NewAssetSourcePreviewResponseAllOfSummaryWithDefaults instantiates a new AssetSourcePreviewResponseAllOfSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetSourcePreviewResponseAllOfSummaryWithDefaults() *AssetSourcePreviewResponseAllOfSummary {
	this := AssetSourcePreviewResponseAllOfSummary{}
	return &this
}

// GetTotalAssets returns the TotalAssets field value
func (o *AssetSourcePreviewResponseAllOfSummary) GetTotalAssets() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalAssets
}

// GetTotalAssetsOk returns a tuple with the TotalAssets field value
// and a boolean to check if the value has been set.
func (o *AssetSourcePreviewResponseAllOfSummary) GetTotalAssetsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalAssets, true
}

// SetTotalAssets sets field value
func (o *AssetSourcePreviewResponseAllOfSummary) SetTotalAssets(v int32) {
	o.TotalAssets = v
}

// GetIncludedAssets returns the IncludedAssets field value
func (o *AssetSourcePreviewResponseAllOfSummary) GetIncludedAssets() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IncludedAssets
}

// GetIncludedAssetsOk returns a tuple with the IncludedAssets field value
// and a boolean to check if the value has been set.
func (o *AssetSourcePreviewResponseAllOfSummary) GetIncludedAssetsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludedAssets, true
}

// SetIncludedAssets sets field value
func (o *AssetSourcePreviewResponseAllOfSummary) SetIncludedAssets(v int32) {
	o.IncludedAssets = v
}

// GetExcludedAssets returns the ExcludedAssets field value
func (o *AssetSourcePreviewResponseAllOfSummary) GetExcludedAssets() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExcludedAssets
}

// GetExcludedAssetsOk returns a tuple with the ExcludedAssets field value
// and a boolean to check if the value has been set.
func (o *AssetSourcePreviewResponseAllOfSummary) GetExcludedAssetsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExcludedAssets, true
}

// SetExcludedAssets sets field value
func (o *AssetSourcePreviewResponseAllOfSummary) SetExcludedAssets(v int32) {
	o.ExcludedAssets = v
}

func (o AssetSourcePreviewResponseAllOfSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetSourcePreviewResponseAllOfSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["totalAssets"] = o.TotalAssets
	toSerialize["includedAssets"] = o.IncludedAssets
	toSerialize["excludedAssets"] = o.ExcludedAssets
	return toSerialize, nil
}

type NullableAssetSourcePreviewResponseAllOfSummary struct {
	value *AssetSourcePreviewResponseAllOfSummary
	isSet bool
}

func (v NullableAssetSourcePreviewResponseAllOfSummary) Get() *AssetSourcePreviewResponseAllOfSummary {
	return v.value
}

func (v *NullableAssetSourcePreviewResponseAllOfSummary) Set(val *AssetSourcePreviewResponseAllOfSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetSourcePreviewResponseAllOfSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetSourcePreviewResponseAllOfSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetSourcePreviewResponseAllOfSummary(val *AssetSourcePreviewResponseAllOfSummary) *NullableAssetSourcePreviewResponseAllOfSummary {
	return &NullableAssetSourcePreviewResponseAllOfSummary{value: val, isSet: true}
}

func (v NullableAssetSourcePreviewResponseAllOfSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetSourcePreviewResponseAllOfSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
