/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ToolCallingConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToolCallingConfig{}

// ToolCallingConfig Validated vLLM tool-calling arguments for this model. When present, these values have been tested end-to-end (tool call request, correct tool_calls output, tool response round-trip) on the target hardware.
type ToolCallingConfig struct {
	// The --tool-call-parser argument value for vLLM serve.
	ToolCallParser *string `json:"toolCallParser,omitempty"`
	// Path to the chat template file, as used with the --chat-template argument. For RHOAI deployments, paths are converted from examples/_* to opt/app-root/template/_*.
	ChatTemplate *string `json:"chatTemplate,omitempty"`
	// Whether to pass --enable-auto-tool-choice to vLLM serve.
	EnableAutoToolChoice *bool `json:"enableAutoToolChoice,omitempty"`
	// Additional CLI arguments required for tool calling beyond the parser, template, and auto-tool-choice flags. Each entry is a complete argument (e.g., \"--config_format mistral\").
	RequiredArgs []string `json:"requiredArgs,omitempty"`
}

// NewToolCallingConfig instantiates a new ToolCallingConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToolCallingConfig() *ToolCallingConfig {
	this := ToolCallingConfig{}
	var enableAutoToolChoice bool = true
	this.EnableAutoToolChoice = &enableAutoToolChoice
	return &this
}

// NewToolCallingConfigWithDefaults instantiates a new ToolCallingConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToolCallingConfigWithDefaults() *ToolCallingConfig {
	this := ToolCallingConfig{}
	var enableAutoToolChoice bool = true
	this.EnableAutoToolChoice = &enableAutoToolChoice
	return &this
}

// GetToolCallParser returns the ToolCallParser field value if set, zero value otherwise.
func (o *ToolCallingConfig) GetToolCallParser() string {
	if o == nil || IsNil(o.ToolCallParser) {
		var ret string
		return ret
	}
	return *o.ToolCallParser
}

// GetToolCallParserOk returns a tuple with the ToolCallParser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ToolCallingConfig) GetToolCallParserOk() (*string, bool) {
	if o == nil || IsNil(o.ToolCallParser) {
		return nil, false
	}
	return o.ToolCallParser, true
}

// HasToolCallParser returns a boolean if a field has been set.
func (o *ToolCallingConfig) HasToolCallParser() bool {
	if o != nil && !IsNil(o.ToolCallParser) {
		return true
	}

	return false
}

// SetToolCallParser gets a reference to the given string and assigns it to the ToolCallParser field.
func (o *ToolCallingConfig) SetToolCallParser(v string) {
	o.ToolCallParser = &v
}

// GetChatTemplate returns the ChatTemplate field value if set, zero value otherwise.
func (o *ToolCallingConfig) GetChatTemplate() string {
	if o == nil || IsNil(o.ChatTemplate) {
		var ret string
		return ret
	}
	return *o.ChatTemplate
}

// GetChatTemplateOk returns a tuple with the ChatTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ToolCallingConfig) GetChatTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.ChatTemplate) {
		return nil, false
	}
	return o.ChatTemplate, true
}

// HasChatTemplate returns a boolean if a field has been set.
func (o *ToolCallingConfig) HasChatTemplate() bool {
	if o != nil && !IsNil(o.ChatTemplate) {
		return true
	}

	return false
}

// SetChatTemplate gets a reference to the given string and assigns it to the ChatTemplate field.
func (o *ToolCallingConfig) SetChatTemplate(v string) {
	o.ChatTemplate = &v
}

// GetEnableAutoToolChoice returns the EnableAutoToolChoice field value if set, zero value otherwise.
func (o *ToolCallingConfig) GetEnableAutoToolChoice() bool {
	if o == nil || IsNil(o.EnableAutoToolChoice) {
		var ret bool
		return ret
	}
	return *o.EnableAutoToolChoice
}

// GetEnableAutoToolChoiceOk returns a tuple with the EnableAutoToolChoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ToolCallingConfig) GetEnableAutoToolChoiceOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableAutoToolChoice) {
		return nil, false
	}
	return o.EnableAutoToolChoice, true
}

// HasEnableAutoToolChoice returns a boolean if a field has been set.
func (o *ToolCallingConfig) HasEnableAutoToolChoice() bool {
	if o != nil && !IsNil(o.EnableAutoToolChoice) {
		return true
	}

	return false
}

// SetEnableAutoToolChoice gets a reference to the given bool and assigns it to the EnableAutoToolChoice field.
func (o *ToolCallingConfig) SetEnableAutoToolChoice(v bool) {
	o.EnableAutoToolChoice = &v
}

// GetRequiredArgs returns the RequiredArgs field value if set, zero value otherwise.
func (o *ToolCallingConfig) GetRequiredArgs() []string {
	if o == nil || IsNil(o.RequiredArgs) {
		var ret []string
		return ret
	}
	return o.RequiredArgs
}

// GetRequiredArgsOk returns a tuple with the RequiredArgs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ToolCallingConfig) GetRequiredArgsOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredArgs) {
		return nil, false
	}
	return o.RequiredArgs, true
}

// HasRequiredArgs returns a boolean if a field has been set.
func (o *ToolCallingConfig) HasRequiredArgs() bool {
	if o != nil && !IsNil(o.RequiredArgs) {
		return true
	}

	return false
}

// SetRequiredArgs gets a reference to the given []string and assigns it to the RequiredArgs field.
func (o *ToolCallingConfig) SetRequiredArgs(v []string) {
	o.RequiredArgs = v
}

func (o ToolCallingConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToolCallingConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ToolCallParser) {
		toSerialize["toolCallParser"] = o.ToolCallParser
	}
	if !IsNil(o.ChatTemplate) {
		toSerialize["chatTemplate"] = o.ChatTemplate
	}
	if !IsNil(o.EnableAutoToolChoice) {
		toSerialize["enableAutoToolChoice"] = o.EnableAutoToolChoice
	}
	if !IsNil(o.RequiredArgs) {
		toSerialize["requiredArgs"] = o.RequiredArgs
	}
	return toSerialize, nil
}

type NullableToolCallingConfig struct {
	value *ToolCallingConfig
	isSet bool
}

func (v NullableToolCallingConfig) Get() *ToolCallingConfig {
	return v.value
}

func (v *NullableToolCallingConfig) Set(val *ToolCallingConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableToolCallingConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableToolCallingConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolCallingConfig(val *ToolCallingConfig) *NullableToolCallingConfig {
	return &NullableToolCallingConfig{value: val, isSet: true}
}

func (v NullableToolCallingConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolCallingConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
