/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Skill type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Skill{}

// Skill An agent skill in the skill catalog. Indexed from a `SKILL.md` in a git repository per the Agent Skills specification (https://agentskills.io).
type Skill struct {
	// User provided custom properties which are not defined by its type.
	CustomProperties map[string]MetadataValue `json:"customProperties,omitempty"`
	// Short description of the skill from the SKILL.md frontmatter.
	Description *string `json:"description,omitempty"`
	// The external id that come from the clients’ system. This field is optional. If set, it must be unique among all resources within a database instance.
	ExternalId *string `json:"externalId,omitempty"`
	// Skill identifier from the SKILL.md frontmatter. Must be unique within a source and version.
	Name string `json:"name"`
	// The unique server generated id of the resource.
	Id *string `json:"id,omitempty"`
	// Output only. Create time of the resource in millisecond since epoch.
	CreateTimeSinceEpoch *string `json:"createTimeSinceEpoch,omitempty"`
	// Output only. Last update time of the resource since epoch in millisecond since epoch.
	LastUpdateTimeSinceEpoch *string `json:"lastUpdateTimeSinceEpoch,omitempty"`
	// Short name of the skill's license (e.g., apache-2.0).
	License *string `json:"license,omitempty"`
	// Author of the skill, from the SKILL.md frontmatter (`author`, or `metadata.author`).
	Author *string `json:"author,omitempty"`
	// Compatibility information declared in the SKILL.md frontmatter (e.g., supported clients or versions).
	Compatibility *string `json:"compatibility,omitempty"`
	// Tools the skill is permitted to use (`allowed-tools` in the SKILL.md frontmatter).
	AllowedTools []string `json:"allowedTools,omitempty"`
	// The SKILL.md body rendered as Markdown documentation.
	Readme *string `json:"readme,omitempty"`
	// Canonical upstream git repository URL. Together with `path` this forms the skill's permanent identity, stable across index rebuilds and mirror deployments.
	Repository *string `json:"repository,omitempty"`
	// Directory of the skill within the repository (the folder containing its SKILL.md).
	Path *string `json:"path,omitempty"`
	// The ref this entry was resolved at (tag, release, or commit). A branch ref is surfaced as `latest` rather than the raw branch name.
	Version *string `json:"version,omitempty"`
	// The exact commit SHA the `version` ref resolved to at sync, used to pin reproducible installs.
	ResolvedCommit *string `json:"resolvedCommit,omitempty"`
	// Catalog source that provides this entity.
	SourceId  *string         `json:"source_id,omitempty"`
	TrustTier *SkillTrustTier `json:"trustTier,omitempty"`
	// Name of the organization or entity that provides the skill.
	Provider *string `json:"provider,omitempty"`
	// Category assigned to the skill in the source configuration.
	Category *string `json:"category,omitempty"`
	// Labels for categorization and filtering.
	Labels []string `json:"labels,omitempty"`
	// Paths of files that accompany the SKILL.md in the skill directory. Contents are not stored; these link back to the repository.
	SupportingFiles []string `json:"supportingFiles,omitempty"`
	// Number of lines in the SKILL.md body, surfaced for skills whose body exceeds recommended length.
	BodyLineCount *int32 `json:"bodyLineCount,omitempty"`
}

type _Skill Skill

// NewSkill instantiates a new Skill object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkill(name string) *Skill {
	this := Skill{}
	this.Name = name
	return &this
}

// NewSkillWithDefaults instantiates a new Skill object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkillWithDefaults() *Skill {
	this := Skill{}
	return &this
}

// GetCustomProperties returns the CustomProperties field value if set, zero value otherwise.
func (o *Skill) GetCustomProperties() map[string]MetadataValue {
	if o == nil || IsNil(o.CustomProperties) {
		var ret map[string]MetadataValue
		return ret
	}
	return o.CustomProperties
}

// GetCustomPropertiesOk returns a tuple with the CustomProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetCustomPropertiesOk() (map[string]MetadataValue, bool) {
	if o == nil || IsNil(o.CustomProperties) {
		return map[string]MetadataValue{}, false
	}
	return o.CustomProperties, true
}

// HasCustomProperties returns a boolean if a field has been set.
func (o *Skill) HasCustomProperties() bool {
	if o != nil && !IsNil(o.CustomProperties) {
		return true
	}

	return false
}

// SetCustomProperties gets a reference to the given map[string]MetadataValue and assigns it to the CustomProperties field.
func (o *Skill) SetCustomProperties(v map[string]MetadataValue) {
	o.CustomProperties = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Skill) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Skill) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Skill) SetDescription(v string) {
	o.Description = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *Skill) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *Skill) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *Skill) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetName returns the Name field value
func (o *Skill) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Skill) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Skill) SetName(v string) {
	o.Name = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Skill) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Skill) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Skill) SetId(v string) {
	o.Id = &v
}

// GetCreateTimeSinceEpoch returns the CreateTimeSinceEpoch field value if set, zero value otherwise.
func (o *Skill) GetCreateTimeSinceEpoch() string {
	if o == nil || IsNil(o.CreateTimeSinceEpoch) {
		var ret string
		return ret
	}
	return *o.CreateTimeSinceEpoch
}

// GetCreateTimeSinceEpochOk returns a tuple with the CreateTimeSinceEpoch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetCreateTimeSinceEpochOk() (*string, bool) {
	if o == nil || IsNil(o.CreateTimeSinceEpoch) {
		return nil, false
	}
	return o.CreateTimeSinceEpoch, true
}

// HasCreateTimeSinceEpoch returns a boolean if a field has been set.
func (o *Skill) HasCreateTimeSinceEpoch() bool {
	if o != nil && !IsNil(o.CreateTimeSinceEpoch) {
		return true
	}

	return false
}

// SetCreateTimeSinceEpoch gets a reference to the given string and assigns it to the CreateTimeSinceEpoch field.
func (o *Skill) SetCreateTimeSinceEpoch(v string) {
	o.CreateTimeSinceEpoch = &v
}

// GetLastUpdateTimeSinceEpoch returns the LastUpdateTimeSinceEpoch field value if set, zero value otherwise.
func (o *Skill) GetLastUpdateTimeSinceEpoch() string {
	if o == nil || IsNil(o.LastUpdateTimeSinceEpoch) {
		var ret string
		return ret
	}
	return *o.LastUpdateTimeSinceEpoch
}

// GetLastUpdateTimeSinceEpochOk returns a tuple with the LastUpdateTimeSinceEpoch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetLastUpdateTimeSinceEpochOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdateTimeSinceEpoch) {
		return nil, false
	}
	return o.LastUpdateTimeSinceEpoch, true
}

// HasLastUpdateTimeSinceEpoch returns a boolean if a field has been set.
func (o *Skill) HasLastUpdateTimeSinceEpoch() bool {
	if o != nil && !IsNil(o.LastUpdateTimeSinceEpoch) {
		return true
	}

	return false
}

// SetLastUpdateTimeSinceEpoch gets a reference to the given string and assigns it to the LastUpdateTimeSinceEpoch field.
func (o *Skill) SetLastUpdateTimeSinceEpoch(v string) {
	o.LastUpdateTimeSinceEpoch = &v
}

// GetLicense returns the License field value if set, zero value otherwise.
func (o *Skill) GetLicense() string {
	if o == nil || IsNil(o.License) {
		var ret string
		return ret
	}
	return *o.License
}

// GetLicenseOk returns a tuple with the License field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetLicenseOk() (*string, bool) {
	if o == nil || IsNil(o.License) {
		return nil, false
	}
	return o.License, true
}

// HasLicense returns a boolean if a field has been set.
func (o *Skill) HasLicense() bool {
	if o != nil && !IsNil(o.License) {
		return true
	}

	return false
}

// SetLicense gets a reference to the given string and assigns it to the License field.
func (o *Skill) SetLicense(v string) {
	o.License = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *Skill) GetAuthor() string {
	if o == nil || IsNil(o.Author) {
		var ret string
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetAuthorOk() (*string, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *Skill) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given string and assigns it to the Author field.
func (o *Skill) SetAuthor(v string) {
	o.Author = &v
}

// GetCompatibility returns the Compatibility field value if set, zero value otherwise.
func (o *Skill) GetCompatibility() string {
	if o == nil || IsNil(o.Compatibility) {
		var ret string
		return ret
	}
	return *o.Compatibility
}

// GetCompatibilityOk returns a tuple with the Compatibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetCompatibilityOk() (*string, bool) {
	if o == nil || IsNil(o.Compatibility) {
		return nil, false
	}
	return o.Compatibility, true
}

// HasCompatibility returns a boolean if a field has been set.
func (o *Skill) HasCompatibility() bool {
	if o != nil && !IsNil(o.Compatibility) {
		return true
	}

	return false
}

// SetCompatibility gets a reference to the given string and assigns it to the Compatibility field.
func (o *Skill) SetCompatibility(v string) {
	o.Compatibility = &v
}

// GetAllowedTools returns the AllowedTools field value if set, zero value otherwise.
func (o *Skill) GetAllowedTools() []string {
	if o == nil || IsNil(o.AllowedTools) {
		var ret []string
		return ret
	}
	return o.AllowedTools
}

// GetAllowedToolsOk returns a tuple with the AllowedTools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetAllowedToolsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedTools) {
		return nil, false
	}
	return o.AllowedTools, true
}

// HasAllowedTools returns a boolean if a field has been set.
func (o *Skill) HasAllowedTools() bool {
	if o != nil && !IsNil(o.AllowedTools) {
		return true
	}

	return false
}

// SetAllowedTools gets a reference to the given []string and assigns it to the AllowedTools field.
func (o *Skill) SetAllowedTools(v []string) {
	o.AllowedTools = v
}

// GetReadme returns the Readme field value if set, zero value otherwise.
func (o *Skill) GetReadme() string {
	if o == nil || IsNil(o.Readme) {
		var ret string
		return ret
	}
	return *o.Readme
}

// GetReadmeOk returns a tuple with the Readme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetReadmeOk() (*string, bool) {
	if o == nil || IsNil(o.Readme) {
		return nil, false
	}
	return o.Readme, true
}

// HasReadme returns a boolean if a field has been set.
func (o *Skill) HasReadme() bool {
	if o != nil && !IsNil(o.Readme) {
		return true
	}

	return false
}

// SetReadme gets a reference to the given string and assigns it to the Readme field.
func (o *Skill) SetReadme(v string) {
	o.Readme = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *Skill) GetRepository() string {
	if o == nil || IsNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetRepositoryOk() (*string, bool) {
	if o == nil || IsNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *Skill) HasRepository() bool {
	if o != nil && !IsNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *Skill) SetRepository(v string) {
	o.Repository = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *Skill) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *Skill) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *Skill) SetPath(v string) {
	o.Path = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Skill) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Skill) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *Skill) SetVersion(v string) {
	o.Version = &v
}

// GetResolvedCommit returns the ResolvedCommit field value if set, zero value otherwise.
func (o *Skill) GetResolvedCommit() string {
	if o == nil || IsNil(o.ResolvedCommit) {
		var ret string
		return ret
	}
	return *o.ResolvedCommit
}

// GetResolvedCommitOk returns a tuple with the ResolvedCommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetResolvedCommitOk() (*string, bool) {
	if o == nil || IsNil(o.ResolvedCommit) {
		return nil, false
	}
	return o.ResolvedCommit, true
}

// HasResolvedCommit returns a boolean if a field has been set.
func (o *Skill) HasResolvedCommit() bool {
	if o != nil && !IsNil(o.ResolvedCommit) {
		return true
	}

	return false
}

// SetResolvedCommit gets a reference to the given string and assigns it to the ResolvedCommit field.
func (o *Skill) SetResolvedCommit(v string) {
	o.ResolvedCommit = &v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *Skill) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *Skill) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *Skill) SetSourceId(v string) {
	o.SourceId = &v
}

// GetTrustTier returns the TrustTier field value if set, zero value otherwise.
func (o *Skill) GetTrustTier() SkillTrustTier {
	if o == nil || IsNil(o.TrustTier) {
		var ret SkillTrustTier
		return ret
	}
	return *o.TrustTier
}

// GetTrustTierOk returns a tuple with the TrustTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetTrustTierOk() (*SkillTrustTier, bool) {
	if o == nil || IsNil(o.TrustTier) {
		return nil, false
	}
	return o.TrustTier, true
}

// HasTrustTier returns a boolean if a field has been set.
func (o *Skill) HasTrustTier() bool {
	if o != nil && !IsNil(o.TrustTier) {
		return true
	}

	return false
}

// SetTrustTier gets a reference to the given SkillTrustTier and assigns it to the TrustTier field.
func (o *Skill) SetTrustTier(v SkillTrustTier) {
	o.TrustTier = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *Skill) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *Skill) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *Skill) SetProvider(v string) {
	o.Provider = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *Skill) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *Skill) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *Skill) SetCategory(v string) {
	o.Category = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Skill) GetLabels() []string {
	if o == nil || IsNil(o.Labels) {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Skill) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *Skill) SetLabels(v []string) {
	o.Labels = v
}

// GetSupportingFiles returns the SupportingFiles field value if set, zero value otherwise.
func (o *Skill) GetSupportingFiles() []string {
	if o == nil || IsNil(o.SupportingFiles) {
		var ret []string
		return ret
	}
	return o.SupportingFiles
}

// GetSupportingFilesOk returns a tuple with the SupportingFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetSupportingFilesOk() ([]string, bool) {
	if o == nil || IsNil(o.SupportingFiles) {
		return nil, false
	}
	return o.SupportingFiles, true
}

// HasSupportingFiles returns a boolean if a field has been set.
func (o *Skill) HasSupportingFiles() bool {
	if o != nil && !IsNil(o.SupportingFiles) {
		return true
	}

	return false
}

// SetSupportingFiles gets a reference to the given []string and assigns it to the SupportingFiles field.
func (o *Skill) SetSupportingFiles(v []string) {
	o.SupportingFiles = v
}

// GetBodyLineCount returns the BodyLineCount field value if set, zero value otherwise.
func (o *Skill) GetBodyLineCount() int32 {
	if o == nil || IsNil(o.BodyLineCount) {
		var ret int32
		return ret
	}
	return *o.BodyLineCount
}

// GetBodyLineCountOk returns a tuple with the BodyLineCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Skill) GetBodyLineCountOk() (*int32, bool) {
	if o == nil || IsNil(o.BodyLineCount) {
		return nil, false
	}
	return o.BodyLineCount, true
}

// HasBodyLineCount returns a boolean if a field has been set.
func (o *Skill) HasBodyLineCount() bool {
	if o != nil && !IsNil(o.BodyLineCount) {
		return true
	}

	return false
}

// SetBodyLineCount gets a reference to the given int32 and assigns it to the BodyLineCount field.
func (o *Skill) SetBodyLineCount(v int32) {
	o.BodyLineCount = &v
}

func (o Skill) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Skill) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomProperties) {
		toSerialize["customProperties"] = o.CustomProperties
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreateTimeSinceEpoch) {
		toSerialize["createTimeSinceEpoch"] = o.CreateTimeSinceEpoch
	}
	if !IsNil(o.LastUpdateTimeSinceEpoch) {
		toSerialize["lastUpdateTimeSinceEpoch"] = o.LastUpdateTimeSinceEpoch
	}
	if !IsNil(o.License) {
		toSerialize["license"] = o.License
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Compatibility) {
		toSerialize["compatibility"] = o.Compatibility
	}
	if !IsNil(o.AllowedTools) {
		toSerialize["allowedTools"] = o.AllowedTools
	}
	if !IsNil(o.Readme) {
		toSerialize["readme"] = o.Readme
	}
	if !IsNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.ResolvedCommit) {
		toSerialize["resolvedCommit"] = o.ResolvedCommit
	}
	if !IsNil(o.SourceId) {
		toSerialize["source_id"] = o.SourceId
	}
	if !IsNil(o.TrustTier) {
		toSerialize["trustTier"] = o.TrustTier
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.SupportingFiles) {
		toSerialize["supportingFiles"] = o.SupportingFiles
	}
	if !IsNil(o.BodyLineCount) {
		toSerialize["bodyLineCount"] = o.BodyLineCount
	}
	return toSerialize, nil
}

type NullableSkill struct {
	value *Skill
	isSet bool
}

func (v NullableSkill) Get() *Skill {
	return v.value
}

func (v *NullableSkill) Set(val *Skill) {
	v.value = val
	v.isSet = true
}

func (v NullableSkill) IsSet() bool {
	return v.isSet
}

func (v *NullableSkill) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkill(val *Skill) *NullableSkill {
	return &NullableSkill{value: val, isSet: true}
}

func (v NullableSkill) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkill) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
