/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SupportedModelFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupportedModelFormat{}

// SupportedModelFormat A model format a runtime can serve. Maps to ServingRuntime.spec.supportedModelFormats[].
type SupportedModelFormat struct {
	// Format name.
	Name string `json:"name"`
	// Optional format version.
	Version *string `json:"version,omitempty"`
	// Whether this runtime may be auto-selected for the format.
	AutoSelect *bool `json:"autoSelect,omitempty"`
	// Selection priority when multiple runtimes support the format.
	Priority *int32 `json:"priority,omitempty"`
}

type _SupportedModelFormat SupportedModelFormat

// NewSupportedModelFormat instantiates a new SupportedModelFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedModelFormat(name string) *SupportedModelFormat {
	this := SupportedModelFormat{}
	this.Name = name
	var autoSelect bool = false
	this.AutoSelect = &autoSelect
	return &this
}

// NewSupportedModelFormatWithDefaults instantiates a new SupportedModelFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedModelFormatWithDefaults() *SupportedModelFormat {
	this := SupportedModelFormat{}
	var autoSelect bool = false
	this.AutoSelect = &autoSelect
	return &this
}

// GetName returns the Name field value
func (o *SupportedModelFormat) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SupportedModelFormat) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SupportedModelFormat) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SupportedModelFormat) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportedModelFormat) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SupportedModelFormat) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *SupportedModelFormat) SetVersion(v string) {
	o.Version = &v
}

// GetAutoSelect returns the AutoSelect field value if set, zero value otherwise.
func (o *SupportedModelFormat) GetAutoSelect() bool {
	if o == nil || IsNil(o.AutoSelect) {
		var ret bool
		return ret
	}
	return *o.AutoSelect
}

// GetAutoSelectOk returns a tuple with the AutoSelect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportedModelFormat) GetAutoSelectOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoSelect) {
		return nil, false
	}
	return o.AutoSelect, true
}

// HasAutoSelect returns a boolean if a field has been set.
func (o *SupportedModelFormat) HasAutoSelect() bool {
	if o != nil && !IsNil(o.AutoSelect) {
		return true
	}

	return false
}

// SetAutoSelect gets a reference to the given bool and assigns it to the AutoSelect field.
func (o *SupportedModelFormat) SetAutoSelect(v bool) {
	o.AutoSelect = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *SupportedModelFormat) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportedModelFormat) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *SupportedModelFormat) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *SupportedModelFormat) SetPriority(v int32) {
	o.Priority = &v
}

func (o SupportedModelFormat) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupportedModelFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.AutoSelect) {
		toSerialize["autoSelect"] = o.AutoSelect
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

type NullableSupportedModelFormat struct {
	value *SupportedModelFormat
	isSet bool
}

func (v NullableSupportedModelFormat) Get() *SupportedModelFormat {
	return v.value
}

func (v *NullableSupportedModelFormat) Set(val *SupportedModelFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedModelFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedModelFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedModelFormat(val *SupportedModelFormat) *NullableSupportedModelFormat {
	return &NullableSupportedModelFormat{value: val, isSet: true}
}

func (v NullableSupportedModelFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedModelFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
