/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServingConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServingConfig{}

// ServingConfig Serving and deployment configuration for the model. Each property represents a distinct configuration concern with its own typed schema. All properties are optional.
type ServingConfig struct {
	ToolCalling *ToolCallingConfig `json:"toolCalling,omitempty"`
}

// NewServingConfig instantiates a new ServingConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServingConfig() *ServingConfig {
	this := ServingConfig{}
	return &this
}

// NewServingConfigWithDefaults instantiates a new ServingConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServingConfigWithDefaults() *ServingConfig {
	this := ServingConfig{}
	return &this
}

// GetToolCalling returns the ToolCalling field value if set, zero value otherwise.
func (o *ServingConfig) GetToolCalling() ToolCallingConfig {
	if o == nil || IsNil(o.ToolCalling) {
		var ret ToolCallingConfig
		return ret
	}
	return *o.ToolCalling
}

// GetToolCallingOk returns a tuple with the ToolCalling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingConfig) GetToolCallingOk() (*ToolCallingConfig, bool) {
	if o == nil || IsNil(o.ToolCalling) {
		return nil, false
	}
	return o.ToolCalling, true
}

// HasToolCalling returns a boolean if a field has been set.
func (o *ServingConfig) HasToolCalling() bool {
	if o != nil && !IsNil(o.ToolCalling) {
		return true
	}

	return false
}

// SetToolCalling gets a reference to the given ToolCallingConfig and assigns it to the ToolCalling field.
func (o *ServingConfig) SetToolCalling(v ToolCallingConfig) {
	o.ToolCalling = &v
}

func (o ServingConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServingConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ToolCalling) {
		toSerialize["toolCalling"] = o.ToolCalling
	}
	return toSerialize, nil
}

type NullableServingConfig struct {
	value *ServingConfig
	isSet bool
}

func (v NullableServingConfig) Get() *ServingConfig {
	return v.value
}

func (v *NullableServingConfig) Set(val *ServingConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableServingConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableServingConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServingConfig(val *ServingConfig) *NullableServingConfig {
	return &NullableServingConfig{value: val, isSet: true}
}

func (v NullableServingConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServingConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
