/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServingRuntimeEnvVar type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServingRuntimeEnvVar{}

// ServingRuntimeEnvVar An environment variable the runtime accepts. Discovery hint only; never carries secret values.
type ServingRuntimeEnvVar struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Required    *bool   `json:"required,omitempty"`
	// Default value for optional, non-secret variables only.
	DefaultValue *string `json:"defaultValue,omitempty"`
	// Whether the value should come from a Secret (never defaulted).
	Secret *bool `json:"secret,omitempty"`
}

type _ServingRuntimeEnvVar ServingRuntimeEnvVar

// NewServingRuntimeEnvVar instantiates a new ServingRuntimeEnvVar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServingRuntimeEnvVar(name string) *ServingRuntimeEnvVar {
	this := ServingRuntimeEnvVar{}
	this.Name = name
	var required bool = false
	this.Required = &required
	var secret bool = false
	this.Secret = &secret
	return &this
}

// NewServingRuntimeEnvVarWithDefaults instantiates a new ServingRuntimeEnvVar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServingRuntimeEnvVarWithDefaults() *ServingRuntimeEnvVar {
	this := ServingRuntimeEnvVar{}
	var required bool = false
	this.Required = &required
	var secret bool = false
	this.Secret = &secret
	return &this
}

// GetName returns the Name field value
func (o *ServingRuntimeEnvVar) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeEnvVar) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServingRuntimeEnvVar) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServingRuntimeEnvVar) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeEnvVar) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServingRuntimeEnvVar) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServingRuntimeEnvVar) SetDescription(v string) {
	o.Description = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *ServingRuntimeEnvVar) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeEnvVar) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *ServingRuntimeEnvVar) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *ServingRuntimeEnvVar) SetRequired(v bool) {
	o.Required = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *ServingRuntimeEnvVar) GetDefaultValue() string {
	if o == nil || IsNil(o.DefaultValue) {
		var ret string
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeEnvVar) GetDefaultValueOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *ServingRuntimeEnvVar) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given string and assigns it to the DefaultValue field.
func (o *ServingRuntimeEnvVar) SetDefaultValue(v string) {
	o.DefaultValue = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *ServingRuntimeEnvVar) GetSecret() bool {
	if o == nil || IsNil(o.Secret) {
		var ret bool
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeEnvVar) GetSecretOk() (*bool, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *ServingRuntimeEnvVar) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given bool and assigns it to the Secret field.
func (o *ServingRuntimeEnvVar) SetSecret(v bool) {
	o.Secret = &v
}

func (o ServingRuntimeEnvVar) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServingRuntimeEnvVar) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	return toSerialize, nil
}

type NullableServingRuntimeEnvVar struct {
	value *ServingRuntimeEnvVar
	isSet bool
}

func (v NullableServingRuntimeEnvVar) Get() *ServingRuntimeEnvVar {
	return v.value
}

func (v *NullableServingRuntimeEnvVar) Set(val *ServingRuntimeEnvVar) {
	v.value = val
	v.isSet = true
}

func (v NullableServingRuntimeEnvVar) IsSet() bool {
	return v.isSet
}

func (v *NullableServingRuntimeEnvVar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServingRuntimeEnvVar(val *ServingRuntimeEnvVar) *NullableServingRuntimeEnvVar {
	return &NullableServingRuntimeEnvVar{value: val, isSet: true}
}

func (v NullableServingRuntimeEnvVar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServingRuntimeEnvVar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
