/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServingRuntimeResourceRecommendation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServingRuntimeResourceRecommendation{}

// ServingRuntimeResourceRecommendation Recommended resource requests/limits for deploying a runtime version. Users should adjust based on model size and traffic.
type ServingRuntimeResourceRecommendation struct {
	Minimal     *ResourceTier `json:"minimal,omitempty"`
	Recommended *ResourceTier `json:"recommended,omitempty"`
	High        *ResourceTier `json:"high,omitempty"`
}

// NewServingRuntimeResourceRecommendation instantiates a new ServingRuntimeResourceRecommendation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServingRuntimeResourceRecommendation() *ServingRuntimeResourceRecommendation {
	this := ServingRuntimeResourceRecommendation{}
	return &this
}

// NewServingRuntimeResourceRecommendationWithDefaults instantiates a new ServingRuntimeResourceRecommendation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServingRuntimeResourceRecommendationWithDefaults() *ServingRuntimeResourceRecommendation {
	this := ServingRuntimeResourceRecommendation{}
	return &this
}

// GetMinimal returns the Minimal field value if set, zero value otherwise.
func (o *ServingRuntimeResourceRecommendation) GetMinimal() ResourceTier {
	if o == nil || IsNil(o.Minimal) {
		var ret ResourceTier
		return ret
	}
	return *o.Minimal
}

// GetMinimalOk returns a tuple with the Minimal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeResourceRecommendation) GetMinimalOk() (*ResourceTier, bool) {
	if o == nil || IsNil(o.Minimal) {
		return nil, false
	}
	return o.Minimal, true
}

// HasMinimal returns a boolean if a field has been set.
func (o *ServingRuntimeResourceRecommendation) HasMinimal() bool {
	if o != nil && !IsNil(o.Minimal) {
		return true
	}

	return false
}

// SetMinimal gets a reference to the given ResourceTier and assigns it to the Minimal field.
func (o *ServingRuntimeResourceRecommendation) SetMinimal(v ResourceTier) {
	o.Minimal = &v
}

// GetRecommended returns the Recommended field value if set, zero value otherwise.
func (o *ServingRuntimeResourceRecommendation) GetRecommended() ResourceTier {
	if o == nil || IsNil(o.Recommended) {
		var ret ResourceTier
		return ret
	}
	return *o.Recommended
}

// GetRecommendedOk returns a tuple with the Recommended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeResourceRecommendation) GetRecommendedOk() (*ResourceTier, bool) {
	if o == nil || IsNil(o.Recommended) {
		return nil, false
	}
	return o.Recommended, true
}

// HasRecommended returns a boolean if a field has been set.
func (o *ServingRuntimeResourceRecommendation) HasRecommended() bool {
	if o != nil && !IsNil(o.Recommended) {
		return true
	}

	return false
}

// SetRecommended gets a reference to the given ResourceTier and assigns it to the Recommended field.
func (o *ServingRuntimeResourceRecommendation) SetRecommended(v ResourceTier) {
	o.Recommended = &v
}

// GetHigh returns the High field value if set, zero value otherwise.
func (o *ServingRuntimeResourceRecommendation) GetHigh() ResourceTier {
	if o == nil || IsNil(o.High) {
		var ret ResourceTier
		return ret
	}
	return *o.High
}

// GetHighOk returns a tuple with the High field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeResourceRecommendation) GetHighOk() (*ResourceTier, bool) {
	if o == nil || IsNil(o.High) {
		return nil, false
	}
	return o.High, true
}

// HasHigh returns a boolean if a field has been set.
func (o *ServingRuntimeResourceRecommendation) HasHigh() bool {
	if o != nil && !IsNil(o.High) {
		return true
	}

	return false
}

// SetHigh gets a reference to the given ResourceTier and assigns it to the High field.
func (o *ServingRuntimeResourceRecommendation) SetHigh(v ResourceTier) {
	o.High = &v
}

func (o ServingRuntimeResourceRecommendation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServingRuntimeResourceRecommendation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Minimal) {
		toSerialize["minimal"] = o.Minimal
	}
	if !IsNil(o.Recommended) {
		toSerialize["recommended"] = o.Recommended
	}
	if !IsNil(o.High) {
		toSerialize["high"] = o.High
	}
	return toSerialize, nil
}

type NullableServingRuntimeResourceRecommendation struct {
	value *ServingRuntimeResourceRecommendation
	isSet bool
}

func (v NullableServingRuntimeResourceRecommendation) Get() *ServingRuntimeResourceRecommendation {
	return v.value
}

func (v *NullableServingRuntimeResourceRecommendation) Set(val *ServingRuntimeResourceRecommendation) {
	v.value = val
	v.isSet = true
}

func (v NullableServingRuntimeResourceRecommendation) IsSet() bool {
	return v.isSet
}

func (v *NullableServingRuntimeResourceRecommendation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServingRuntimeResourceRecommendation(val *ServingRuntimeResourceRecommendation) *NullableServingRuntimeResourceRecommendation {
	return &NullableServingRuntimeResourceRecommendation{value: val, isSet: true}
}

func (v NullableServingRuntimeResourceRecommendation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServingRuntimeResourceRecommendation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
