/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServingRuntimeVersionList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServingRuntimeVersionList{}

// ServingRuntimeVersionList A list of serving_runtime_version entities.
type ServingRuntimeVersionList struct {
	// Token to use to retrieve next page of results.
	NextPageToken string `json:"nextPageToken"`
	// Maximum number of resources to return in the result.
	PageSize int32 `json:"pageSize"`
	// Number of items in result list.
	Size int32 `json:"size"`
	// Array of `ServingRuntimeVersion` entities.
	Items []ServingRuntimeVersion `json:"items"`
}

type _ServingRuntimeVersionList ServingRuntimeVersionList

// NewServingRuntimeVersionList instantiates a new ServingRuntimeVersionList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServingRuntimeVersionList(nextPageToken string, pageSize int32, size int32, items []ServingRuntimeVersion) *ServingRuntimeVersionList {
	this := ServingRuntimeVersionList{}
	this.NextPageToken = nextPageToken
	this.PageSize = pageSize
	this.Size = size
	this.Items = items
	return &this
}

// NewServingRuntimeVersionListWithDefaults instantiates a new ServingRuntimeVersionList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServingRuntimeVersionListWithDefaults() *ServingRuntimeVersionList {
	this := ServingRuntimeVersionList{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value
func (o *ServingRuntimeVersionList) GetNextPageToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersionList) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPageToken, true
}

// SetNextPageToken sets field value
func (o *ServingRuntimeVersionList) SetNextPageToken(v string) {
	o.NextPageToken = v
}

// GetPageSize returns the PageSize field value
func (o *ServingRuntimeVersionList) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersionList) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *ServingRuntimeVersionList) SetPageSize(v int32) {
	o.PageSize = v
}

// GetSize returns the Size field value
func (o *ServingRuntimeVersionList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersionList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ServingRuntimeVersionList) SetSize(v int32) {
	o.Size = v
}

// GetItems returns the Items field value
func (o *ServingRuntimeVersionList) GetItems() []ServingRuntimeVersion {
	if o == nil {
		var ret []ServingRuntimeVersion
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersionList) GetItemsOk() ([]ServingRuntimeVersion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ServingRuntimeVersionList) SetItems(v []ServingRuntimeVersion) {
	o.Items = v
}

func (o ServingRuntimeVersionList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServingRuntimeVersionList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nextPageToken"] = o.NextPageToken
	toSerialize["pageSize"] = o.PageSize
	toSerialize["size"] = o.Size
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableServingRuntimeVersionList struct {
	value *ServingRuntimeVersionList
	isSet bool
}

func (v NullableServingRuntimeVersionList) Get() *ServingRuntimeVersionList {
	return v.value
}

func (v *NullableServingRuntimeVersionList) Set(val *ServingRuntimeVersionList) {
	v.value = val
	v.isSet = true
}

func (v NullableServingRuntimeVersionList) IsSet() bool {
	return v.isSet
}

func (v *NullableServingRuntimeVersionList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServingRuntimeVersionList(val *ServingRuntimeVersionList) *NullableServingRuntimeVersionList {
	return &NullableServingRuntimeVersionList{value: val, isSet: true}
}

func (v NullableServingRuntimeVersionList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServingRuntimeVersionList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
