/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SkillList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkillList{}

// SkillList A list of skill entities.
type SkillList struct {
	// Token to use to retrieve next page of results.
	NextPageToken string `json:"nextPageToken"`
	// Maximum number of resources to return in the result.
	PageSize int32 `json:"pageSize"`
	// Number of items in result list.
	Size int32 `json:"size"`
	// Array of `Skill` entities.
	Items []Skill `json:"items"`
}

type _SkillList SkillList

// NewSkillList instantiates a new SkillList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkillList(nextPageToken string, pageSize int32, size int32, items []Skill) *SkillList {
	this := SkillList{}
	this.NextPageToken = nextPageToken
	this.PageSize = pageSize
	this.Size = size
	this.Items = items
	return &this
}

// NewSkillListWithDefaults instantiates a new SkillList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkillListWithDefaults() *SkillList {
	this := SkillList{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value
func (o *SkillList) GetNextPageToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
func (o *SkillList) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPageToken, true
}

// SetNextPageToken sets field value
func (o *SkillList) SetNextPageToken(v string) {
	o.NextPageToken = v
}

// GetPageSize returns the PageSize field value
func (o *SkillList) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *SkillList) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *SkillList) SetPageSize(v int32) {
	o.PageSize = v
}

// GetSize returns the Size field value
func (o *SkillList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *SkillList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *SkillList) SetSize(v int32) {
	o.Size = v
}

// GetItems returns the Items field value
func (o *SkillList) GetItems() []Skill {
	if o == nil {
		var ret []Skill
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SkillList) GetItemsOk() ([]Skill, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *SkillList) SetItems(v []Skill) {
	o.Items = v
}

func (o SkillList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkillList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nextPageToken"] = o.NextPageToken
	toSerialize["pageSize"] = o.PageSize
	toSerialize["size"] = o.Size
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableSkillList struct {
	value *SkillList
	isSet bool
}

func (v NullableSkillList) Get() *SkillList {
	return v.value
}

func (v *NullableSkillList) Set(val *SkillList) {
	v.value = val
	v.isSet = true
}

func (v NullableSkillList) IsSet() bool {
	return v.isSet
}

func (v *NullableSkillList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkillList(val *SkillList) *NullableSkillList {
	return &NullableSkillList{value: val, isSet: true}
}

func (v NullableSkillList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkillList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
