/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PreviewCatalogSourceResponse - Polymorphic preview response. The `assetType` discriminator determines whether the payload is a model preview or an MCP server preview.
type PreviewCatalogSourceResponse struct {
	AssetSourcePreviewResponse   *AssetSourcePreviewResponse
	CatalogSourcePreviewResponse *CatalogSourcePreviewResponse
}

// AssetSourcePreviewResponseAsPreviewCatalogSourceResponse is a convenience function that returns AssetSourcePreviewResponse wrapped in PreviewCatalogSourceResponse
func AssetSourcePreviewResponseAsPreviewCatalogSourceResponse(v *AssetSourcePreviewResponse) PreviewCatalogSourceResponse {
	return PreviewCatalogSourceResponse{
		AssetSourcePreviewResponse: v,
	}
}

// CatalogSourcePreviewResponseAsPreviewCatalogSourceResponse is a convenience function that returns CatalogSourcePreviewResponse wrapped in PreviewCatalogSourceResponse
func CatalogSourcePreviewResponseAsPreviewCatalogSourceResponse(v *CatalogSourcePreviewResponse) PreviewCatalogSourceResponse {
	return PreviewCatalogSourceResponse{
		CatalogSourcePreviewResponse: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PreviewCatalogSourceResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mcp_servers'
	if jsonDict["assetType"] == "mcp_servers" {
		// try to unmarshal JSON data into AssetSourcePreviewResponse
		err = json.Unmarshal(data, &dst.AssetSourcePreviewResponse)
		if err == nil {
			return nil // data stored in dst.AssetSourcePreviewResponse, return on the first match
		} else {
			dst.AssetSourcePreviewResponse = nil
			return fmt.Errorf("failed to unmarshal PreviewCatalogSourceResponse as AssetSourcePreviewResponse: %s", err.Error())
		}
	}

	// check if the discriminator value is 'models'
	if jsonDict["assetType"] == "models" {
		// try to unmarshal JSON data into CatalogSourcePreviewResponse
		err = json.Unmarshal(data, &dst.CatalogSourcePreviewResponse)
		if err == nil {
			return nil // data stored in dst.CatalogSourcePreviewResponse, return on the first match
		} else {
			dst.CatalogSourcePreviewResponse = nil
			return fmt.Errorf("failed to unmarshal PreviewCatalogSourceResponse as CatalogSourcePreviewResponse: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PreviewCatalogSourceResponse) MarshalJSON() ([]byte, error) {
	if src.AssetSourcePreviewResponse != nil {
		return json.Marshal(&src.AssetSourcePreviewResponse)
	}

	if src.CatalogSourcePreviewResponse != nil {
		return json.Marshal(&src.CatalogSourcePreviewResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PreviewCatalogSourceResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.AssetSourcePreviewResponse != nil {
		return obj.AssetSourcePreviewResponse
	}

	if obj.CatalogSourcePreviewResponse != nil {
		return obj.CatalogSourcePreviewResponse
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PreviewCatalogSourceResponse) GetActualInstanceValue() interface{} {
	if obj.AssetSourcePreviewResponse != nil {
		return *obj.AssetSourcePreviewResponse
	}

	if obj.CatalogSourcePreviewResponse != nil {
		return *obj.CatalogSourcePreviewResponse
	}

	// all schemas are nil
	return nil
}

type NullablePreviewCatalogSourceResponse struct {
	value *PreviewCatalogSourceResponse
	isSet bool
}

func (v NullablePreviewCatalogSourceResponse) Get() *PreviewCatalogSourceResponse {
	return v.value
}

func (v *NullablePreviewCatalogSourceResponse) Set(val *PreviewCatalogSourceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePreviewCatalogSourceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePreviewCatalogSourceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreviewCatalogSourceResponse(val *PreviewCatalogSourceResponse) *NullablePreviewCatalogSourceResponse {
	return &NullablePreviewCatalogSourceResponse{value: val, isSet: true}
}

func (v NullablePreviewCatalogSourceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreviewCatalogSourceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
