/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MCPStorageMount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPStorageMount{}

// MCPStorageMount struct for MCPStorageMount
type MCPStorageMount struct {
	// Absolute mount path inside the container.
	Path string `json:"path"`
	// Mount permissions. Defaults to ReadOnly when unset.
	Permissions *string          `json:"permissions,omitempty"`
	Source      MCPStorageSource `json:"source"`
}

type _MCPStorageMount MCPStorageMount

// NewMCPStorageMount instantiates a new MCPStorageMount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPStorageMount(path string, source MCPStorageSource) *MCPStorageMount {
	this := MCPStorageMount{}
	this.Path = path
	this.Source = source
	return &this
}

// NewMCPStorageMountWithDefaults instantiates a new MCPStorageMount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPStorageMountWithDefaults() *MCPStorageMount {
	this := MCPStorageMount{}
	return &this
}

// GetPath returns the Path field value
func (o *MCPStorageMount) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *MCPStorageMount) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *MCPStorageMount) SetPath(v string) {
	o.Path = v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *MCPStorageMount) GetPermissions() string {
	if o == nil || IsNil(o.Permissions) {
		var ret string
		return ret
	}
	return *o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MCPStorageMount) GetPermissionsOk() (*string, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *MCPStorageMount) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given string and assigns it to the Permissions field.
func (o *MCPStorageMount) SetPermissions(v string) {
	o.Permissions = &v
}

// GetSource returns the Source field value
func (o *MCPStorageMount) GetSource() MCPStorageSource {
	if o == nil {
		var ret MCPStorageSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *MCPStorageMount) GetSourceOk() (*MCPStorageSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *MCPStorageMount) SetSource(v MCPStorageSource) {
	o.Source = v
}

func (o MCPStorageMount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPStorageMount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

type NullableMCPStorageMount struct {
	value *MCPStorageMount
	isSet bool
}

func (v NullableMCPStorageMount) Get() *MCPStorageMount {
	return v.value
}

func (v *NullableMCPStorageMount) Set(val *MCPStorageMount) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPStorageMount) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPStorageMount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPStorageMount(val *MCPStorageMount) *NullableMCPStorageMount {
	return &NullableMCPStorageMount{value: val, isSet: true}
}

func (v NullableMCPStorageMount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPStorageMount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
