/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SkillTrustTier Provenance label applied to a skill from its source configuration. A plain label shown as a badge and usable for filtering; it carries no ordering or special semantics. Downstream products may map these to their own display names.
type SkillTrustTier string

// List of SkillTrustTier
const (
	SKILLTRUSTTIER_PLATFORM_PROVIDED     SkillTrustTier = "platformProvided"
	SKILLTRUSTTIER_PARTNER_VERIFIED      SkillTrustTier = "partnerVerified"
	SKILLTRUSTTIER_ORGANIZATION_APPROVED SkillTrustTier = "organizationApproved"
	SKILLTRUSTTIER_COMMUNITY_CONTRIBUTED SkillTrustTier = "communityContributed"
)

// All allowed values of SkillTrustTier enum
var AllowedSkillTrustTierEnumValues = []SkillTrustTier{
	"platformProvided",
	"partnerVerified",
	"organizationApproved",
	"communityContributed",
}

func (v *SkillTrustTier) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SkillTrustTier(value)
	for _, existing := range AllowedSkillTrustTierEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SkillTrustTier", value)
}

// NewSkillTrustTierFromValue returns a pointer to a valid SkillTrustTier
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSkillTrustTierFromValue(v string) (*SkillTrustTier, error) {
	ev := SkillTrustTier(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SkillTrustTier: valid values are %v", v, AllowedSkillTrustTierEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SkillTrustTier) IsValid() bool {
	for _, existing := range AllowedSkillTrustTierEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SkillTrustTier value
func (v SkillTrustTier) Ptr() *SkillTrustTier {
	return &v
}

type NullableSkillTrustTier struct {
	value *SkillTrustTier
	isSet bool
}

func (v NullableSkillTrustTier) Get() *SkillTrustTier {
	return v.value
}

func (v *NullableSkillTrustTier) Set(val *SkillTrustTier) {
	v.value = val
	v.isSet = true
}

func (v NullableSkillTrustTier) IsSet() bool {
	return v.isSet
}

func (v *NullableSkillTrustTier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkillTrustTier(val *SkillTrustTier) *NullableSkillTrustTier {
	return &NullableSkillTrustTier{value: val, isSet: true}
}

func (v NullableSkillTrustTier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkillTrustTier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
