/*
Catalog REST API

REST API for Kubeflow Hub Catalog

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ServingRuntimeVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServingRuntimeVersion{}

// ServingRuntimeVersion A specific, deployable version of a serving runtime. Carries the container image and the metadata needed to generate a ServingRuntime manifest. Discovery metadata only — not a live deployment.
type ServingRuntimeVersion struct {
	// User provided custom properties which are not defined by its type.
	CustomProperties map[string]MetadataValue `json:"customProperties,omitempty"`
	// An optional description about the resource.
	Description *string `json:"description,omitempty"`
	// The external id that come from the clients’ system. This field is optional. If set, it must be unique among all resources within a database instance.
	ExternalId *string `json:"externalId,omitempty"`
	// The client provided name of the artifact. This field is optional. If set, it must be unique among all the artifacts of the same artifact type within a database instance and cannot be changed once set.
	Name *string `json:"name,omitempty"`
	// The unique server generated id of the resource.
	Id *string `json:"id,omitempty"`
	// Output only. Create time of the resource in millisecond since epoch.
	CreateTimeSinceEpoch *string `json:"createTimeSinceEpoch,omitempty"`
	// Output only. Last update time of the resource since epoch in millisecond since epoch.
	LastUpdateTimeSinceEpoch *string `json:"lastUpdateTimeSinceEpoch,omitempty"`
	ArtifactType             string  `json:"artifactType"`
	// Version string of the runtime (typically the image tag).
	Version string `json:"version"`
	// Fully-qualified container image reference for this version. The registry host may be rewritten by the dashboard for disconnected environments (registry mirror override).
	Image        string                      `json:"image"`
	SupportLevel *ServingRuntimeSupportLevel `json:"supportLevel,omitempty"`
	// Model formats supported by this specific version.
	SupportedModelFormats []SupportedModelFormat `json:"supportedModelFormats,omitempty"`
	// Inference protocols supported (maps to ServingRuntime.spec.protocolVersions).
	ProtocolVersions     []string                              `json:"protocolVersions,omitempty"`
	RecommendedResources *ServingRuntimeResourceRecommendation `json:"recommendedResources,omitempty"`
	// Default container args for the generated ServingRuntime.
	DefaultArgs []string `json:"defaultArgs,omitempty"`
	// Environment variables the runtime accepts (discovery hints; no secret values).
	Env []ServingRuntimeEnvVar `json:"env,omitempty"`
	// Optional full ServingRuntime (KServe v1alpha1) manifest for this version, as a JSON-encoded string, ready for review/edit before creation. If omitted, the consumer generates the manifest from the fields above.
	Template *string `json:"template,omitempty"`
	// Whether this version is deprecated and should be de-emphasized in the UI.
	Deprecated *bool `json:"deprecated,omitempty"`
	// Publication timestamp for this version/image.
	PublishedDate *time.Time `json:"publishedDate,omitempty"`
}

type _ServingRuntimeVersion ServingRuntimeVersion

// NewServingRuntimeVersion instantiates a new ServingRuntimeVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServingRuntimeVersion(artifactType string, version string, image string) *ServingRuntimeVersion {
	this := ServingRuntimeVersion{}
	this.ArtifactType = artifactType
	this.Version = version
	this.Image = image
	var deprecated bool = false
	this.Deprecated = &deprecated
	return &this
}

// NewServingRuntimeVersionWithDefaults instantiates a new ServingRuntimeVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServingRuntimeVersionWithDefaults() *ServingRuntimeVersion {
	this := ServingRuntimeVersion{}
	var artifactType string = "serving-runtime-version"
	this.ArtifactType = artifactType
	var deprecated bool = false
	this.Deprecated = &deprecated
	return &this
}

// GetCustomProperties returns the CustomProperties field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetCustomProperties() map[string]MetadataValue {
	if o == nil || IsNil(o.CustomProperties) {
		var ret map[string]MetadataValue
		return ret
	}
	return o.CustomProperties
}

// GetCustomPropertiesOk returns a tuple with the CustomProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetCustomPropertiesOk() (map[string]MetadataValue, bool) {
	if o == nil || IsNil(o.CustomProperties) {
		return map[string]MetadataValue{}, false
	}
	return o.CustomProperties, true
}

// HasCustomProperties returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasCustomProperties() bool {
	if o != nil && !IsNil(o.CustomProperties) {
		return true
	}

	return false
}

// SetCustomProperties gets a reference to the given map[string]MetadataValue and assigns it to the CustomProperties field.
func (o *ServingRuntimeVersion) SetCustomProperties(v map[string]MetadataValue) {
	o.CustomProperties = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServingRuntimeVersion) SetDescription(v string) {
	o.Description = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *ServingRuntimeVersion) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServingRuntimeVersion) SetName(v string) {
	o.Name = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ServingRuntimeVersion) SetId(v string) {
	o.Id = &v
}

// GetCreateTimeSinceEpoch returns the CreateTimeSinceEpoch field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetCreateTimeSinceEpoch() string {
	if o == nil || IsNil(o.CreateTimeSinceEpoch) {
		var ret string
		return ret
	}
	return *o.CreateTimeSinceEpoch
}

// GetCreateTimeSinceEpochOk returns a tuple with the CreateTimeSinceEpoch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetCreateTimeSinceEpochOk() (*string, bool) {
	if o == nil || IsNil(o.CreateTimeSinceEpoch) {
		return nil, false
	}
	return o.CreateTimeSinceEpoch, true
}

// HasCreateTimeSinceEpoch returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasCreateTimeSinceEpoch() bool {
	if o != nil && !IsNil(o.CreateTimeSinceEpoch) {
		return true
	}

	return false
}

// SetCreateTimeSinceEpoch gets a reference to the given string and assigns it to the CreateTimeSinceEpoch field.
func (o *ServingRuntimeVersion) SetCreateTimeSinceEpoch(v string) {
	o.CreateTimeSinceEpoch = &v
}

// GetLastUpdateTimeSinceEpoch returns the LastUpdateTimeSinceEpoch field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetLastUpdateTimeSinceEpoch() string {
	if o == nil || IsNil(o.LastUpdateTimeSinceEpoch) {
		var ret string
		return ret
	}
	return *o.LastUpdateTimeSinceEpoch
}

// GetLastUpdateTimeSinceEpochOk returns a tuple with the LastUpdateTimeSinceEpoch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetLastUpdateTimeSinceEpochOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdateTimeSinceEpoch) {
		return nil, false
	}
	return o.LastUpdateTimeSinceEpoch, true
}

// HasLastUpdateTimeSinceEpoch returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasLastUpdateTimeSinceEpoch() bool {
	if o != nil && !IsNil(o.LastUpdateTimeSinceEpoch) {
		return true
	}

	return false
}

// SetLastUpdateTimeSinceEpoch gets a reference to the given string and assigns it to the LastUpdateTimeSinceEpoch field.
func (o *ServingRuntimeVersion) SetLastUpdateTimeSinceEpoch(v string) {
	o.LastUpdateTimeSinceEpoch = &v
}

// GetArtifactType returns the ArtifactType field value
func (o *ServingRuntimeVersion) GetArtifactType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArtifactType
}

// GetArtifactTypeOk returns a tuple with the ArtifactType field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetArtifactTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArtifactType, true
}

// SetArtifactType sets field value
func (o *ServingRuntimeVersion) SetArtifactType(v string) {
	o.ArtifactType = v
}

// GetVersion returns the Version field value
func (o *ServingRuntimeVersion) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ServingRuntimeVersion) SetVersion(v string) {
	o.Version = v
}

// GetImage returns the Image field value
func (o *ServingRuntimeVersion) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *ServingRuntimeVersion) SetImage(v string) {
	o.Image = v
}

// GetSupportLevel returns the SupportLevel field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetSupportLevel() ServingRuntimeSupportLevel {
	if o == nil || IsNil(o.SupportLevel) {
		var ret ServingRuntimeSupportLevel
		return ret
	}
	return *o.SupportLevel
}

// GetSupportLevelOk returns a tuple with the SupportLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetSupportLevelOk() (*ServingRuntimeSupportLevel, bool) {
	if o == nil || IsNil(o.SupportLevel) {
		return nil, false
	}
	return o.SupportLevel, true
}

// HasSupportLevel returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasSupportLevel() bool {
	if o != nil && !IsNil(o.SupportLevel) {
		return true
	}

	return false
}

// SetSupportLevel gets a reference to the given ServingRuntimeSupportLevel and assigns it to the SupportLevel field.
func (o *ServingRuntimeVersion) SetSupportLevel(v ServingRuntimeSupportLevel) {
	o.SupportLevel = &v
}

// GetSupportedModelFormats returns the SupportedModelFormats field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetSupportedModelFormats() []SupportedModelFormat {
	if o == nil || IsNil(o.SupportedModelFormats) {
		var ret []SupportedModelFormat
		return ret
	}
	return o.SupportedModelFormats
}

// GetSupportedModelFormatsOk returns a tuple with the SupportedModelFormats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetSupportedModelFormatsOk() ([]SupportedModelFormat, bool) {
	if o == nil || IsNil(o.SupportedModelFormats) {
		return nil, false
	}
	return o.SupportedModelFormats, true
}

// HasSupportedModelFormats returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasSupportedModelFormats() bool {
	if o != nil && !IsNil(o.SupportedModelFormats) {
		return true
	}

	return false
}

// SetSupportedModelFormats gets a reference to the given []SupportedModelFormat and assigns it to the SupportedModelFormats field.
func (o *ServingRuntimeVersion) SetSupportedModelFormats(v []SupportedModelFormat) {
	o.SupportedModelFormats = v
}

// GetProtocolVersions returns the ProtocolVersions field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetProtocolVersions() []string {
	if o == nil || IsNil(o.ProtocolVersions) {
		var ret []string
		return ret
	}
	return o.ProtocolVersions
}

// GetProtocolVersionsOk returns a tuple with the ProtocolVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetProtocolVersionsOk() ([]string, bool) {
	if o == nil || IsNil(o.ProtocolVersions) {
		return nil, false
	}
	return o.ProtocolVersions, true
}

// HasProtocolVersions returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasProtocolVersions() bool {
	if o != nil && !IsNil(o.ProtocolVersions) {
		return true
	}

	return false
}

// SetProtocolVersions gets a reference to the given []string and assigns it to the ProtocolVersions field.
func (o *ServingRuntimeVersion) SetProtocolVersions(v []string) {
	o.ProtocolVersions = v
}

// GetRecommendedResources returns the RecommendedResources field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetRecommendedResources() ServingRuntimeResourceRecommendation {
	if o == nil || IsNil(o.RecommendedResources) {
		var ret ServingRuntimeResourceRecommendation
		return ret
	}
	return *o.RecommendedResources
}

// GetRecommendedResourcesOk returns a tuple with the RecommendedResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetRecommendedResourcesOk() (*ServingRuntimeResourceRecommendation, bool) {
	if o == nil || IsNil(o.RecommendedResources) {
		return nil, false
	}
	return o.RecommendedResources, true
}

// HasRecommendedResources returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasRecommendedResources() bool {
	if o != nil && !IsNil(o.RecommendedResources) {
		return true
	}

	return false
}

// SetRecommendedResources gets a reference to the given ServingRuntimeResourceRecommendation and assigns it to the RecommendedResources field.
func (o *ServingRuntimeVersion) SetRecommendedResources(v ServingRuntimeResourceRecommendation) {
	o.RecommendedResources = &v
}

// GetDefaultArgs returns the DefaultArgs field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetDefaultArgs() []string {
	if o == nil || IsNil(o.DefaultArgs) {
		var ret []string
		return ret
	}
	return o.DefaultArgs
}

// GetDefaultArgsOk returns a tuple with the DefaultArgs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetDefaultArgsOk() ([]string, bool) {
	if o == nil || IsNil(o.DefaultArgs) {
		return nil, false
	}
	return o.DefaultArgs, true
}

// HasDefaultArgs returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasDefaultArgs() bool {
	if o != nil && !IsNil(o.DefaultArgs) {
		return true
	}

	return false
}

// SetDefaultArgs gets a reference to the given []string and assigns it to the DefaultArgs field.
func (o *ServingRuntimeVersion) SetDefaultArgs(v []string) {
	o.DefaultArgs = v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetEnv() []ServingRuntimeEnvVar {
	if o == nil || IsNil(o.Env) {
		var ret []ServingRuntimeEnvVar
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetEnvOk() ([]ServingRuntimeEnvVar, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given []ServingRuntimeEnvVar and assigns it to the Env field.
func (o *ServingRuntimeVersion) SetEnv(v []ServingRuntimeEnvVar) {
	o.Env = v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetTemplate() string {
	if o == nil || IsNil(o.Template) {
		var ret string
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasTemplate() bool {
	if o != nil && !IsNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given string and assigns it to the Template field.
func (o *ServingRuntimeVersion) SetTemplate(v string) {
	o.Template = &v
}

// GetDeprecated returns the Deprecated field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetDeprecated() bool {
	if o == nil || IsNil(o.Deprecated) {
		var ret bool
		return ret
	}
	return *o.Deprecated
}

// GetDeprecatedOk returns a tuple with the Deprecated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetDeprecatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deprecated) {
		return nil, false
	}
	return o.Deprecated, true
}

// HasDeprecated returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasDeprecated() bool {
	if o != nil && !IsNil(o.Deprecated) {
		return true
	}

	return false
}

// SetDeprecated gets a reference to the given bool and assigns it to the Deprecated field.
func (o *ServingRuntimeVersion) SetDeprecated(v bool) {
	o.Deprecated = &v
}

// GetPublishedDate returns the PublishedDate field value if set, zero value otherwise.
func (o *ServingRuntimeVersion) GetPublishedDate() time.Time {
	if o == nil || IsNil(o.PublishedDate) {
		var ret time.Time
		return ret
	}
	return *o.PublishedDate
}

// GetPublishedDateOk returns a tuple with the PublishedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServingRuntimeVersion) GetPublishedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PublishedDate) {
		return nil, false
	}
	return o.PublishedDate, true
}

// HasPublishedDate returns a boolean if a field has been set.
func (o *ServingRuntimeVersion) HasPublishedDate() bool {
	if o != nil && !IsNil(o.PublishedDate) {
		return true
	}

	return false
}

// SetPublishedDate gets a reference to the given time.Time and assigns it to the PublishedDate field.
func (o *ServingRuntimeVersion) SetPublishedDate(v time.Time) {
	o.PublishedDate = &v
}

func (o ServingRuntimeVersion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServingRuntimeVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomProperties) {
		toSerialize["customProperties"] = o.CustomProperties
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreateTimeSinceEpoch) {
		toSerialize["createTimeSinceEpoch"] = o.CreateTimeSinceEpoch
	}
	if !IsNil(o.LastUpdateTimeSinceEpoch) {
		toSerialize["lastUpdateTimeSinceEpoch"] = o.LastUpdateTimeSinceEpoch
	}
	toSerialize["artifactType"] = o.ArtifactType
	toSerialize["version"] = o.Version
	toSerialize["image"] = o.Image
	if !IsNil(o.SupportLevel) {
		toSerialize["supportLevel"] = o.SupportLevel
	}
	if !IsNil(o.SupportedModelFormats) {
		toSerialize["supportedModelFormats"] = o.SupportedModelFormats
	}
	if !IsNil(o.ProtocolVersions) {
		toSerialize["protocolVersions"] = o.ProtocolVersions
	}
	if !IsNil(o.RecommendedResources) {
		toSerialize["recommendedResources"] = o.RecommendedResources
	}
	if !IsNil(o.DefaultArgs) {
		toSerialize["defaultArgs"] = o.DefaultArgs
	}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	if !IsNil(o.Deprecated) {
		toSerialize["deprecated"] = o.Deprecated
	}
	if !IsNil(o.PublishedDate) {
		toSerialize["publishedDate"] = o.PublishedDate
	}
	return toSerialize, nil
}

type NullableServingRuntimeVersion struct {
	value *ServingRuntimeVersion
	isSet bool
}

func (v NullableServingRuntimeVersion) Get() *ServingRuntimeVersion {
	return v.value
}

func (v *NullableServingRuntimeVersion) Set(val *ServingRuntimeVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableServingRuntimeVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableServingRuntimeVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServingRuntimeVersion(val *ServingRuntimeVersion) *NullableServingRuntimeVersion {
	return &NullableServingRuntimeVersion{value: val, isSet: true}
}

func (v NullableServingRuntimeVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServingRuntimeVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
