// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog REST API
 *
 * REST API for Kubeflow Hub Catalog
 *
 * API version: v1alpha1
 */

package openapi

import (
	"context"
	"net/http"

	model "github.com/kubeflow/hub/catalog/pkg/openapi"
)

// SkillCatalogServiceAPIRouter defines the required methods for binding the api requests to a responses for the SkillCatalogServiceAPI
// The SkillCatalogServiceAPIRouter implementation should parse necessary information from the http request,
// pass the data to a SkillCatalogServiceAPIServicer to perform the required actions, then write the service results to the http response.
type SkillCatalogServiceAPIRouter interface {
	FindSkills(http.ResponseWriter, *http.Request)
	FindSkillsFilterOptions(http.ResponseWriter, *http.Request)
	GetSkill(http.ResponseWriter, *http.Request)
}

// SkillCatalogServiceAPIServicer defines the api actions for the SkillCatalogServiceAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SkillCatalogServiceAPIServicer interface {
	FindSkills(context.Context, string, string, []string, []string, string, string, model.OrderByField, model.SortOrder, string) (ImplResponse, error)
	FindSkillsFilterOptions(context.Context) (ImplResponse, error)
	GetSkill(context.Context, string) (ImplResponse, error)
}
