// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog REST API
 *
 * REST API for Kubeflow Hub Catalog
 *
 * API version: v1alpha1
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"

	model "github.com/kubeflow/hub/catalog/pkg/openapi"
)

// SkillCatalogServiceAPIController binds http requests to an api service and writes the service results to the http response
type SkillCatalogServiceAPIController struct {
	service      SkillCatalogServiceAPIServicer
	errorHandler ErrorHandler
}

// SkillCatalogServiceAPIOption for how the controller is set up.
type SkillCatalogServiceAPIOption func(*SkillCatalogServiceAPIController)

// WithSkillCatalogServiceAPIErrorHandler inject ErrorHandler into controller
func WithSkillCatalogServiceAPIErrorHandler(h ErrorHandler) SkillCatalogServiceAPIOption {
	return func(c *SkillCatalogServiceAPIController) {
		c.errorHandler = h
	}
}

// NewSkillCatalogServiceAPIController creates a default api controller
func NewSkillCatalogServiceAPIController(s SkillCatalogServiceAPIServicer, opts ...SkillCatalogServiceAPIOption) *SkillCatalogServiceAPIController {
	controller := &SkillCatalogServiceAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the SkillCatalogServiceAPIController
func (c *SkillCatalogServiceAPIController) Routes() Routes {
	return Routes{
		"FindSkills": Route{
			"FindSkills",
			strings.ToUpper("Get"),
			"/api/skill_catalog/v1alpha1/skills",
			c.FindSkills,
		},
		"FindSkillsFilterOptions": Route{
			"FindSkillsFilterOptions",
			strings.ToUpper("Get"),
			"/api/skill_catalog/v1alpha1/skills/filter_options",
			c.FindSkillsFilterOptions,
		},
		"GetSkill": Route{
			"GetSkill",
			strings.ToUpper("Get"),
			"/api/skill_catalog/v1alpha1/skills/{id}",
			c.GetSkill,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the SkillCatalogServiceAPIController
func (c *SkillCatalogServiceAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"FindSkills",
			strings.ToUpper("Get"),
			"/api/skill_catalog/v1alpha1/skills",
			c.FindSkills,
		},
		Route{
			"FindSkillsFilterOptions",
			strings.ToUpper("Get"),
			"/api/skill_catalog/v1alpha1/skills/filter_options",
			c.FindSkillsFilterOptions,
		},
		Route{
			"GetSkill",
			strings.ToUpper("Get"),
			"/api/skill_catalog/v1alpha1/skills/{id}",
			c.GetSkill,
		},
	}
}

// FindSkills - List skills.
func (c *SkillCatalogServiceAPIController) FindSkills(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var nameParam string
	if query.Has("name") {
		param := query.Get("name")

		nameParam = param
	} else {
	}
	var qParam string
	if query.Has("q") {
		param := query.Get("q")

		qParam = param
	} else {
	}
	var sourceParam []string
	if query.Has("source") {
		sourceParam = strings.Split(query.Get("source"), ",")
	}
	var sourceLabelParam []string
	if query.Has("sourceLabel") {
		sourceLabelParam = strings.Split(query.Get("sourceLabel"), ",")
	}
	var filterQueryParam string
	if query.Has("filterQuery") {
		param := query.Get("filterQuery")

		filterQueryParam = param
	} else {
	}
	var pageSizeParam string
	if query.Has("pageSize") {
		param := query.Get("pageSize")

		pageSizeParam = param
	} else {
	}
	var orderByParam model.OrderByField
	if query.Has("orderBy") {
		param := model.OrderByField(query.Get("orderBy"))

		orderByParam = param
	} else {
	}
	var sortOrderParam model.SortOrder
	if query.Has("sortOrder") {
		param := model.SortOrder(query.Get("sortOrder"))

		sortOrderParam = param
	} else {
	}
	var nextPageTokenParam string
	if query.Has("nextPageToken") {
		param := query.Get("nextPageToken")

		nextPageTokenParam = param
	} else {
	}
	result, err := c.service.FindSkills(r.Context(), nameParam, qParam, sourceParam, sourceLabelParam, filterQueryParam, pageSizeParam, orderByParam, sortOrderParam, nextPageTokenParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// FindSkillsFilterOptions - Lists fields and values that can be used in `filterQuery` on the list skills endpoint.
func (c *SkillCatalogServiceAPIController) FindSkillsFilterOptions(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.FindSkillsFilterOptions(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetSkill - Get a skill by ID.
func (c *SkillCatalogServiceAPIController) GetSkill(w http.ResponseWriter, r *http.Request) {
	idParam := chi.URLParam(r, "id")
	if idParam == "" {
		c.errorHandler(w, r, &RequiredError{"id"}, nil)
		return
	}
	result, err := c.service.GetSkill(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
