// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog REST API
 *
 * REST API for Kubeflow Hub Catalog
 *
 * API version: v1alpha1
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"

	model "github.com/kubeflow/hub/catalog/pkg/openapi"
)

// AgentCatalogServiceAPIController binds http requests to an api service and writes the service results to the http response
type AgentCatalogServiceAPIController struct {
	service      AgentCatalogServiceAPIServicer
	errorHandler ErrorHandler
}

// AgentCatalogServiceAPIOption for how the controller is set up.
type AgentCatalogServiceAPIOption func(*AgentCatalogServiceAPIController)

// WithAgentCatalogServiceAPIErrorHandler inject ErrorHandler into controller
func WithAgentCatalogServiceAPIErrorHandler(h ErrorHandler) AgentCatalogServiceAPIOption {
	return func(c *AgentCatalogServiceAPIController) {
		c.errorHandler = h
	}
}

// NewAgentCatalogServiceAPIController creates a default api controller
func NewAgentCatalogServiceAPIController(s AgentCatalogServiceAPIServicer, opts ...AgentCatalogServiceAPIOption) *AgentCatalogServiceAPIController {
	controller := &AgentCatalogServiceAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AgentCatalogServiceAPIController
func (c *AgentCatalogServiceAPIController) Routes() Routes {
	return Routes{
		"FindAgents": Route{
			"FindAgents",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents",
			c.FindAgents,
		},
		"FindAgentsFilterOptions": Route{
			"FindAgentsFilterOptions",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents/filter_options",
			c.FindAgentsFilterOptions,
		},
		"GetAgent": Route{
			"GetAgent",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents/{id}",
			c.GetAgent,
		},
		"GetAgentArtifacts": Route{
			"GetAgentArtifacts",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents/{id}/artifacts",
			c.GetAgentArtifacts,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the AgentCatalogServiceAPIController
func (c *AgentCatalogServiceAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"FindAgents",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents",
			c.FindAgents,
		},
		Route{
			"FindAgentsFilterOptions",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents/filter_options",
			c.FindAgentsFilterOptions,
		},
		Route{
			"GetAgent",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents/{id}",
			c.GetAgent,
		},
		Route{
			"GetAgentArtifacts",
			strings.ToUpper("Get"),
			"/api/agent_catalog/v1alpha1/agents/{id}/artifacts",
			c.GetAgentArtifacts,
		},
	}
}

// FindAgents - List agents.
func (c *AgentCatalogServiceAPIController) FindAgents(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var nameParam string
	if query.Has("name") {
		param := query.Get("name")

		nameParam = param
	} else {
	}
	var qParam string
	if query.Has("q") {
		param := query.Get("q")

		qParam = param
	} else {
	}
	var sourceParam []string
	if query.Has("source") {
		sourceParam = strings.Split(query.Get("source"), ",")
	}
	var sourceLabelParam []string
	if query.Has("sourceLabel") {
		sourceLabelParam = strings.Split(query.Get("sourceLabel"), ",")
	}
	var filterQueryParam string
	if query.Has("filterQuery") {
		param := query.Get("filterQuery")

		filterQueryParam = param
	} else {
	}
	var pageSizeParam string
	if query.Has("pageSize") {
		param := query.Get("pageSize")

		pageSizeParam = param
	} else {
	}
	var orderByParam model.OrderByField
	if query.Has("orderBy") {
		param := model.OrderByField(query.Get("orderBy"))

		orderByParam = param
	} else {
	}
	var sortOrderParam model.SortOrder
	if query.Has("sortOrder") {
		param := model.SortOrder(query.Get("sortOrder"))

		sortOrderParam = param
	} else {
	}
	var nextPageTokenParam string
	if query.Has("nextPageToken") {
		param := query.Get("nextPageToken")

		nextPageTokenParam = param
	} else {
	}
	result, err := c.service.FindAgents(r.Context(), nameParam, qParam, sourceParam, sourceLabelParam, filterQueryParam, pageSizeParam, orderByParam, sortOrderParam, nextPageTokenParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// FindAgentsFilterOptions - Lists fields and values that can be used in `filterQuery` on the list agents endpoint.
func (c *AgentCatalogServiceAPIController) FindAgentsFilterOptions(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.FindAgentsFilterOptions(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetAgent - Get an agent by ID.
func (c *AgentCatalogServiceAPIController) GetAgent(w http.ResponseWriter, r *http.Request) {
	idParam := chi.URLParam(r, "id")
	if idParam == "" {
		c.errorHandler(w, r, &RequiredError{"id"}, nil)
		return
	}
	result, err := c.service.GetAgent(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetAgentArtifacts - List artifacts for an agent.
func (c *AgentCatalogServiceAPIController) GetAgentArtifacts(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	idParam := chi.URLParam(r, "id")
	if idParam == "" {
		c.errorHandler(w, r, &RequiredError{"id"}, nil)
		return
	}
	var artifactTypeParam []model.AgentArtifactTypeQueryParam
	if query.Has("artifactType") {
		paramSplits := strings.Split(query.Get("artifactType"), ",")
		artifactTypeParam = make([]model.AgentArtifactTypeQueryParam, 0, len(paramSplits))
		for _, param := range paramSplits {
			paramEnum, err := model.NewAgentArtifactTypeQueryParamFromValue(param)
			if err != nil {
				c.errorHandler(w, r, &ParsingError{Param: "artifactType", Err: err}, nil)
				return
			}
			artifactTypeParam = append(artifactTypeParam, *paramEnum)
		}
	}
	var pageSizeParam string
	if query.Has("pageSize") {
		param := query.Get("pageSize")

		pageSizeParam = param
	} else {
	}
	var orderByParam model.OrderByField
	if query.Has("orderBy") {
		param := model.OrderByField(query.Get("orderBy"))

		orderByParam = param
	} else {
	}
	var sortOrderParam model.SortOrder
	if query.Has("sortOrder") {
		param := model.SortOrder(query.Get("sortOrder"))

		sortOrderParam = param
	} else {
	}
	var nextPageTokenParam string
	if query.Has("nextPageToken") {
		param := query.Get("nextPageToken")

		nextPageTokenParam = param
	} else {
	}
	result, err := c.service.GetAgentArtifacts(r.Context(), idParam, artifactTypeParam, pageSizeParam, orderByParam, sortOrderParam, nextPageTokenParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
