// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog REST API
 *
 * REST API for Kubeflow Hub Catalog
 *
 * API version: v1alpha1
 */

package openapi

import (
	"context"
	"net/http"

	model "github.com/kubeflow/hub/catalog/pkg/openapi"
)

// AgentCatalogServiceAPIRouter defines the required methods for binding the api requests to a responses for the AgentCatalogServiceAPI
// The AgentCatalogServiceAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AgentCatalogServiceAPIServicer to perform the required actions, then write the service results to the http response.
type AgentCatalogServiceAPIRouter interface {
	FindAgents(http.ResponseWriter, *http.Request)
	FindAgentsFilterOptions(http.ResponseWriter, *http.Request)
	GetAgent(http.ResponseWriter, *http.Request)
	GetAgentArtifacts(http.ResponseWriter, *http.Request)
}

// AgentCatalogServiceAPIServicer defines the api actions for the AgentCatalogServiceAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AgentCatalogServiceAPIServicer interface {
	FindAgents(context.Context, string, string, []string, []string, string, string, model.OrderByField, model.SortOrder, string) (ImplResponse, error)
	FindAgentsFilterOptions(context.Context) (ImplResponse, error)
	GetAgent(context.Context, string) (ImplResponse, error)
	GetAgentArtifacts(context.Context, string, []model.AgentArtifactTypeQueryParam, string, model.OrderByField, model.SortOrder, string) (ImplResponse, error)
}
