import sys
import typing as t
from pathlib import Path
from textwrap import dedent

def get_funcs(models: t.Iterable[Path]) -> t.Iterator[str]:
    for path in models:
        with path.open() as f:
            # skip boilerplate
            lines = iter(f.readlines())
            while not next(lines).startswith("package"):
                continue

            buf = []
            in_func = False
            in_import = False
            for raw in lines:
                line = raw.rstrip()
                if not line and not in_func:
                    continue

                if line.startswith("import "):
                    in_import = True
                    continue
                elif line == ")" and in_import:
                    in_import = False
                    buf.clear()
                    continue

                buf.append(line)
                if line.startswith("func"):
                    in_func = True
                elif line.startswith("}") and in_func:
                    in_func = False
                    yield "\n".join(buf)
                    buf.clear()
        path.unlink()


def get_name(func: str) -> str:
    # each func is declared as:
    # // comment
    # func funcName(args) error ...
    return func.split("\n")[1].split(" ")[1].split("(")[0]


if __name__ == "__main__":
    # model catalog package root
    root = Path(__file__).parent.parent.resolve()
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "internal/server/openapi"
    pkg = src.name

    print(
        dedent(f"""
/*
 * Catalog REST API
 *
 * REST API for Kubeflow Hub Catalog
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 *
 */

// File generated by scripts/gen_type_asserts.sh - DO NOT EDIT

package {pkg}

import (
    model "github.com/kubeflow/hub/catalog/pkg/openapi"
)

    """)
    )
    print(
        "\n".join(
            sorted(
                get_funcs(path for path in src.glob("model_*.go")),
                key=lambda f: get_name(f),
            )
        )
    )
