#!/usr/bin/env bash

set -e

PROJECT_ROOT=$(realpath "$(dirname "$0")"/..)

OUTPUT_DIR="$1"
if [ -z "$OUTPUT_DIR" ]; then
    echo "Usage: $0 <output-dir-relative-to-project-root>"
    exit 1
fi

ASSERT_FILE_PATH="${PROJECT_ROOT}/${OUTPUT_DIR}/type_asserts.go"

python3 "${PROJECT_ROOT}/scripts/gen_type_asserts.py" "${PROJECT_ROOT}/${OUTPUT_DIR}" >"$ASSERT_FILE_PATH"

gofmt -w "$ASSERT_FILE_PATH"

# FIXME(manual): openapi-generator emits incorrect logic for AssertMetadataValueRequired -
# it requires every field to be non-zero, when only one oneOf variant should ever be set.
# Comment out the generated body in place; this replaces a path-dependent `git apply` patch
# so the same fix applies to every generated output directory (v1alpha3, v1, ...).
sed -i -f - "$ASSERT_FILE_PATH" <<'SED_EOF'
/^func AssertMetadataValueRequired/a\
	// FIXME(manual): Wrong autogenerated logic, just one elem should be non-zero.
/^func AssertMetadataValueRequired/,/^}/{
    /^func AssertMetadataValueRequired/b
    /^}$/b
    /^	return nil$/b
    /^$/b
    s/^\t/\t\/\/ /
}
SED_EOF

gofmt -w "$ASSERT_FILE_PATH"
