// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog REST API
 *
 * REST API for Kubeflow Hub Catalog
 *
 * API version: v1
 */

package v1

import (
	"net/http"

	"github.com/go-chi/chi/v5/middleware"
)

func Logger(inner http.Handler) http.Handler {
	return middleware.Logger(inner)
}
