name: Build
on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - "LICENSE*"
      - "DOCKERFILE*"
      - "**.gitignore"
      - "**.md"
      - "**.txt"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/dependabot.yml"
      - "docs/**"
jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Build
        run: make build/compile
      - name: Unit tests
        run: make test-cover
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          files: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
