name: Build and Push async-upload container image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'jobs/async-upload/**'
      - '!LICENSE*'
      - '!DOCKERFILE*'
      - '!**.gitignore'
      - '!**.md'
      - '!**.txt'

env:
  IMG_REGISTRY: quay.io
  IMG_ORG: opendatahub
  IMG_NAME: model-registry-job-async-upload
  REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
  REGISTRY_PWD: ${{ secrets.QUAY_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMG_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PWD }}

    - name: Set main-branch environment # this is for main-sha tag image build
      if: github.ref == 'refs/heads/main'
      run: |
        commit_sha=${{ github.sha }}
        tag=main-${commit_sha:0:7}
        echo "VERSION=${tag}" >> $GITHUB_ENV

    - name: Set tag environment # this is for v* tag image build
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./jobs/async-upload
        push: true
        tags: ${{ env.IMG_REGISTRY }}/${{ env.IMG_ORG }}/${{ env.IMG_NAME }}:${{ env.VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
